// GENERATED by scripts/import-wp.mjs — edit the script or re-run `pnpm import:wp`
// rather than hand-editing, or your changes will be overwritten on the next import.

export interface Img {
  src: string
  alt: string
}

/** Site photography, imported from the WordPress media library. */
export const site = {
  "hero-ski-town": {
    src: "/images/site/hero-ski-town.webp",
    alt: "A small mountain ski town with people walking down main street with a blue sky and large majestic mountains in the background."
  },
  "hero-district": {
    src: "/images/site/hero-district.webp",
    alt: ""
  },
  "hero-mountain": {
    src: "/images/site/hero-mountain.webp",
    alt: "Aerial view of a thriving mountain town surrounded by dramatic peaks, representing The GreyEdge Group’s district-scale teams driving transformational impact and project success."
  },
  "hero-cityscape": {
    src: "/images/site/hero-cityscape.webp",
    alt: ""
  },
  "design-session": {
    src: "/images/site/design-session.webp",
    alt: "The GreyEdge Group with hands over a table looking and designing a TEN system."
  },
  "design-session-alt": {
    src: "/images/site/design-session-alt.webp",
    alt: "The Greyedge team collaborating with clients over a table layout of thermal energy network blueprints and a tablet diagram for System Ten engineering design."
  },
  "design-meeting": {
    src: "/images/site/design-meeting.webp",
    alt: "GreyEdge engineers gathered around a illuminated physical district model reviewing Thermal Energy Network plans, blueprints, and digital engineering data in their design office."
  },
  "team-photo": {
    src: "/images/site/team-photo.webp",
    alt: "GreyEdge's engineers and energy professionals from standing together in an office."
  },
  "team-group": {
    src: "/images/site/team-group.webp",
    alt: "Group of engineers and energy professionals from The GreyEdge Group standing together in an office in front of a thermal energy system presentation"
  },
  "onsite-work": {
    src: "/images/site/onsite-work.webp",
    alt: "GreyEdge team members and developers wearing hard hats review thermal energy network plans at an active construction site."
  },
  "planning-ten": {
    src: "/images/site/planning-ten.webp",
    alt: "A group of geothermal professionals reviewing plans outdoors near campus energy infrastructure surrounded by green landscaping."
  },
  "panel-discussion": {
    src: "/images/site/panel-discussion.webp",
    alt: "The GreyEdge Group team discussing geothermal and thermal energy systems at a panel presentation with an audience"
  },
  conference: {
    src: "/images/site/conference.webp",
    alt: "GreyEdge Discussing Thermal Energy Network Designs"
  },
  puzzle: {
    src: "/images/site/puzzle.webp",
    alt: "GreyEdge team members collaborate by fitting large grey puzzle pieces together."
  },
  "campus-build": {
    src: "/images/site/campus-build.webp",
    alt: "An ariel view of a TEN being developed on a University campus"
  },
  blueprints: {
    src: "/images/site/blueprints.webp",
    alt: "Black and white close-up of rolled architectural blueprints and engineering schematics resting on a dark, textured work surface."
  },
  "mechanical-room": {
    src: "/images/site/mechanical-room.webp",
    alt: "Two engineering professionals in safety vests reviewing industrial mechanical systems inside a large-scale infrastructure facility for The GreyEdge Group"
  },
  "network-diagram": {
    src: "/images/site/network-diagram.webp",
    alt: "Diagram showing TGEG’s ambient loop network, networked heat pump architecture, and geothermal thermal resources working together to heat and cool multi‑building districts."
  },
  "global-projects": {
    src: "/images/site/global-projects.webp",
    alt: ""
  },
  contact: {
    src: "/images/site/contact.webp",
    alt: "A white laptop in an office with a green plant blurred in the background."
  },
  decarbonization: {
    src: "/images/site/decarbonization.webp",
    alt: "Panoramic view of a mid-size city skyline nestled between lush tree canopy and mountain ranges under a clear blue sky, representing the opportunity for urban decarbonization through clean thermal energy systems."
  },
  electrification: {
    src: "/images/site/electrification.webp",
    alt: "Sunlit urban plaza with rows of trees casting long shadows across wide stone pavers, flanked by tall glass and concrete high-rise towers, representing the dense energy demands of modern city districts."
  },
  infrastructure: {
    src: "/images/site/infrastructure.webp",
    alt: "Tree-lined urban plaza with patterned stone pavers running between large commercial buildings and glass skyscrapers, illustrating the existing built infrastructure that new development must work within."
  },
  "lifecycle-cost": {
    src: "/images/site/lifecycle-cost.webp",
    alt: "Modern sustainable campus buildings with wood and metal façades surrounded by mature trees and native plantings, representing long-term infrastructure investment and lifecycle cost planning."
  },
  "growth-flexibility": {
    src: "/images/site/growth-flexibility.webp",
    alt: "Aerial view of a modern city skyline surrounded by greenery, symbolizing sustainable urban growth and adaptable infrastructure."
  }
} satisfies Record<string, Img>

/** Logo and brand marks. */
export const brand = {
  "logo-white": {
    src: "/images/brand/logo-white.webp",
    alt: "Greyedge logo in white on a transparent background"
  },
  "logo-dark": {
    src: "/images/brand/logo-dark.webp",
    alt: "Greyedge Group logo in dark grey on a transparent background"
  },
  "edge-only-white": {
    src: "/images/brand/edge-only-white.webp",
    alt: ""
  },
  favicon: {
    src: "/images/brand/favicon.webp",
    alt: "The Grey Edge Group Favicon"
  }
} satisfies Record<string, Img>
