// GENERATED by scripts/import-wp.mjs — edit the script or re-run `pnpm import:wp`
// rather than hand-editing, or your changes will be overwritten on the next import.

export interface Img {
  src: string
  alt: string
}

/** Site photography, imported from the WordPress media library. */
export const site = {
  "hero-ski-town": {
    src: "/images/site/hero-ski-town.webp",
    alt: "A small mountain ski town with people walking down main street with a blue sky and large majestic mountains in the background."
  },
  "hero-district": {
    src: "/images/site/hero-district.webp",
    alt: "Engineers reviewing a district thermal energy system in a mechanical plant room"
  },
  "hero-mountain": {
    src: "/images/site/hero-mountain.webp",
    alt: "Aerial view of a thriving mountain town surrounded by dramatic peaks, representing The GreyEdge Group’s district-scale teams driving transformational impact and project success."
  },
  "hero-cityscape": {
    src: "/images/site/hero-cityscape.webp",
    alt: "Dense urban skyline served by district-scale thermal infrastructure"
  },
  "design-session": {
    src: "/images/site/design-session.webp",
    alt: "The GreyEdge Group with hands over a table looking and designing a TEN system."
  },
  "design-session-alt": {
    src: "/images/site/design-session-alt.webp",
    alt: "The Greyedge team collaborating with clients over a table layout of thermal energy network blueprints and a tablet diagram for System Ten engineering design."
  },
  "design-meeting": {
    src: "/images/site/design-meeting.webp",
    alt: "GreyEdge engineers gathered around a illuminated physical district model reviewing Thermal Energy Network plans, blueprints, and digital engineering data in their design office."
  },
  "district-scale-site-planning": {
    src: "/images/site/district-scale-thermal-systems-site-planning.webp",
    alt: "Construction and engineering team in hard hats reviewing blueprints and a laptop during an on-site planning meeting for a district-scale thermal energy system."
  },
  "thermal-plant-inspection": {
    src: "/images/site/thermal-plant-engineers-system-inspection.webp",
    alt: "Engineers inspecting industrial thermal plant equipment and piping during a system walkthrough at a heating and cooling facility."
  },
  "advisory-meeting": {
    src: "/images/site/advisory-meeting.webp",
    alt: "Professionals reviewing architectural floor plans together at a table during a planning meeting."
  },
  "training-classroom": {
    src: "/images/site/training-classroom.webp",
    alt: "Instructor explaining an Ambient Temperature Loop diagram on a whiteboard during a professional training session."
  },
  "team-photo": {
    src: "/images/site/team-photo.webp",
    alt: "About ten GreyEdge Group team members standing together indoors in business casual attire for a group portrait."
  },
  "team-group": {
    src: "/images/site/team-group.webp",
    alt: "Group of engineers and energy professionals from The GreyEdge Group standing together in an office in front of a thermal energy system presentation"
  },
  "onsite-work": {
    src: "/images/site/onsite-work.webp",
    alt: "GreyEdge team members and developers wearing hard hats review thermal energy network plans at an active construction site."
  },
  "planning-ten": {
    src: "/images/site/planning-ten.webp",
    alt: "A group of geothermal professionals reviewing plans outdoors near campus energy infrastructure surrounded by green landscaping."
  },
  "panel-discussion": {
    src: "/images/site/panel-discussion.webp",
    alt: "The GreyEdge Group team discussing geothermal and thermal energy systems at a panel presentation with an audience"
  },
  conference: {
    src: "/images/site/conference.webp",
    alt: "GreyEdge Discussing Thermal Energy Network Designs"
  },
  puzzle: {
    src: "/images/site/puzzle.webp",
    alt: "GreyEdge team members collaborate by fitting large grey puzzle pieces together."
  },
  "approach-planning-session": {
    src: "/images/site/approach-planning-session.webp",
    alt: "Engineers and planners reviewing architectural blueprints at a wooden table with hard hats nearby during a collaborative design session."
  },
  "approach-existing-assets": {
    src: "/images/site/approach-existing-assets.webp",
    alt: "Large rooftop cooling towers and industrial HVAC piping on a commercial building under a clear blue sky."
  },
  "shaping-the-future": {
    src: "/images/site/shaping-the-future.webp",
    alt: "Two engineers in hard hats and safety vests reviewing a large infrastructure construction site at sunrise, with a highway overpass in the background."
  },
  "service-planning": {
    src: "/images/site/service-planning.webp",
    alt: "Engineer reviewing architectural blueprints with drafting tools, a laptop, and a building model on a design desk."
  },
  "service-ground": {
    src: "/images/site/service-ground.webp",
    alt: "Large drilling rig with spiral auger at a geothermal borefield construction site at sunset."
  },
  "service-network": {
    src: "/images/site/service-network.webp",
    alt: "Engineering team reviewing floor plans and thermal network blueprints at a table with a hard hat and laptop."
  },
  "service-delivery": {
    src: "/images/site/service-delivery.webp",
    alt: "Aerial view of a campus district with buildings, green spaces, and roads under a bright sky."
  },
  "service-advisory": {
    src: "/images/site/service-advisory.webp",
    alt: "Field professionals in hard hats and safety vests walking through a solar array during a site inspection."
  },
  "campus-build": {
    src: "/images/site/campus-build.webp",
    alt: "An ariel view of a TEN being developed on a University campus"
  },
  blueprints: {
    src: "/images/site/blueprints.webp",
    alt: "Black and white close-up of rolled architectural blueprints and engineering schematics resting on a dark, textured work surface."
  },
  "mechanical-room": {
    src: "/images/site/mechanical-room.webp",
    alt: "Two engineering professionals in safety vests reviewing industrial mechanical systems inside a large-scale infrastructure facility for The GreyEdge Group"
  },
  "network-diagram": {
    src: "/images/site/network-diagram.webp",
    alt: "Diagram showing TGEG’s ambient loop network, networked heat pump architecture, and geothermal thermal resources working together to heat and cool multi‑building districts."
  },
  "global-projects": {
    src: "/images/site/global-projects.webp",
    alt: "Map of GreyEdge thermal energy network projects across the world"
  },
  contact: {
    src: "/images/site/contact.webp",
    alt: "A white laptop in an office with a green plant blurred in the background."
  },
  decarbonization: {
    src: "/images/site/decarbonization.webp",
    alt: "Panoramic view of a mid-size city skyline nestled between lush tree canopy and mountain ranges under a clear blue sky, representing the opportunity for urban decarbonization through clean thermal energy systems."
  },
  electrification: {
    src: "/images/site/electrification.webp",
    alt: "Sunlit urban plaza with rows of trees casting long shadows across wide stone pavers, flanked by tall glass and concrete high-rise towers, representing the dense energy demands of modern city districts."
  },
  infrastructure: {
    src: "/images/site/infrastructure.webp",
    alt: "Tree-lined urban plaza with patterned stone pavers running between large commercial buildings and glass skyscrapers, illustrating the existing built infrastructure that new development must work within."
  },
  "lifecycle-cost": {
    src: "/images/site/lifecycle-cost.webp",
    alt: "Modern sustainable campus buildings with wood and metal façades surrounded by mature trees and native plantings, representing long-term infrastructure investment and lifecycle cost planning."
  },
  "growth-flexibility": {
    src: "/images/site/growth-flexibility.webp",
    alt: "Aerial view of a modern city skyline surrounded by greenery, symbolizing sustainable urban growth and adaptable infrastructure."
  },
  "insight-cmu": {
    src: "/images/site/insight-cmu.webp",
    alt: "Colorado Mesa University campus at sunset with brick buildings, blossoming trees, and the Grand Mesa on the horizon."
  },
  "insight-50-90": {
    src: "/images/site/insight-50-90.webp",
    alt: "Mountain resort village with red-roofed lodges nestled in a green valley under a clear blue sky."
  },
  "insight-first-cost": {
    src: "/images/site/insight-first-cost.webp",
    alt: "Hands reviewing architectural blueprints with drafting tools, a hard hat, and a building model on a wooden table."
  },
  "insight-implementing-tens": {
    src: "/images/site/insight-implementing-tens.webp",
    alt: "Historic small-town main street lined with brick storefronts, autumn trees, and American flags under a bright blue sky."
  },
  "insight-mountain-town": {
    src: "/images/site/insight-mountain-town.webp",
    alt: "Historic mountain-town main street with brick buildings, American flags, and a steep forested peak at the end of the block."
  },
  "insight-weber-state": {
    src: "/images/site/insight-weber-state.webp",
    alt: "Weber State University campus with a fountain reflecting in a pond, clock tower, and the white W on the mountain behind."
  },
  "insight-colorado-policy": {
    src: "/images/site/insight-colorado-policy.webp",
    alt: "Aerial view of a Colorado mountain town surrounded by green forests and snow-capped peaks under a clear blue sky."
  },
  "insight-finance": {
    src: "/images/site/insight-finance.webp",
    alt: "Team reviewing financial charts on a laptop, tablet, and printed reports while taking notes in a notebook."
  },
  "insight-share-a-site": {
    src: "/images/site/insight-share-a-site.webp",
    alt: "Aerial view of a suburban school campus with athletic fields, parking, and surrounding neighborhoods under a blue sky."
  }
} satisfies Record<string, Img>

/** Logo and brand marks. */
export const brand = {
  "logo-white": {
    src: "/images/brand/logo-white.webp",
    alt: "Greyedge logo in white on a transparent background"
  },
  "logo-dark": {
    src: "/images/brand/logo-dark.webp",
    alt: "Greyedge Group logo in dark grey on a transparent background"
  },
  "edge-only-white": {
    src: "/images/brand/edge-only-white.webp",
    alt: "The GreyEdge edge mark"
  },
  favicon: {
    src: "/images/brand/favicon.webp",
    alt: "The Grey Edge Group Favicon"
  }
} satisfies Record<string, Img>
