// GENERATED by scripts/import-wp.mjs — edit the script or re-run `pnpm import:wp`
// rather than hand-editing, or your changes will be overwritten on the next import.

export interface ProjectArticle {
  title: string
  publisher: string
  url: string
}

/** Partner / org credited on a project page. Optional url when the source links them. */
export interface ProjectTeamMember {
  name: string
  url?: string
}

export interface Project {
  slug: string
  name: string
  location: string
  country: string
  sqFeet: string | null
  buildings: string | null
  completion: string | null
  status: 'In Progress' | 'In Development' | 'Operational' | 'Completed'
  summary: string
  description: string | string[]
  /** Project partners / collaborating orgs. Empty when not yet collected. */
  team: ProjectTeamMember[]
  articles: ProjectArticle[]
  image: string | null
  imageAlt: string
  featured: boolean
}

export const projects: Project[] = [
  {
    slug: "aspen",
    name: "Aspen",
    location: "Aspen, CO",
    country: "United States",
    sqFeet: "402,000",
    buildings: "3",
    completion: "In Progress / 2029",
    status: "In Progress",
    summary: "See how the Aspen School District is evaluating next-generation energy infrastructure that supports students, facilities, and long-term sustainability goals.",
    description: "The Aspen School District project demonstrates how educational facilities can use shared thermal infrastructure to support sustainability, comfort, and long-term operational performance in Aspen, Colorado. The proposed Ambient Temperature Loop connects Aspen Elementary School, Aspen Middle School, and Aspen High School into a unified Thermal Energy Network. The campus includes approximately 414,173 square feet of facilities, including conditioned space and snowmelt infrastructure. By linking multiple educational facilities into one system, the district can take advantage of load diversity and shared resources. The project supports district goals for decarbonization, resiliency, and future cooling capability. The GreyEdge Group identified a pathway for modernizing campus infrastructure while maintaining reliable operations. The GreyEdge Group evaluated thermal assets including geoexchange borefields, co-generation, Genesys CLAD technology, solar thermal, wastewater energy recovery, and snowmelt heat recovery. These resources support approximately 709 tons of peak heating and 234 tons of peak cooling capacity. The proposed network is expected to reduce heating-related greenhouse gas emissions by approximately 75 percent, or about 654 metric tons of CO2 annually. The Ambient Temperature Loop provides a flexible platform for future campus expansion and infrastructure upgrades. The project highlights how K-12 campuses can become leaders in sustainable community infrastructure.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Aspen School District", url: "https://www.aspenk12.net/" },
      { name: "McKinstry", url: "https://www.mckinstry.com/" },
      { name: "Holy Cross Energy", url: "https://www.holycross.com/" },
    ],
    articles: [
      {
        title: "Aspen Schools Look Underground For Sustainable Energy For Cooling And Heating",
        publisher: "Big Pivots",
        url: "https://bigpivots.com/aspen-schools-look-underground-for-sustainable-energy-for-cooling-and-heating/"
      },
      {
        title: "ASD Summer Initiatives Underway",
        publisher: "Aspen Daily News",
        url: "https://www.aspendailynews.com/news/asd-summer-initiatives-underway-f50edad5"
      },
      {
        title: "Aspen School District Sees Groundbreaking Success With Foot Geo Bore",
        publisher: "The Aspen Times",
        url: "https://www.aspentimes.com/news/aspen-school-district-sees-groundbreaking-success-with-1000-foot-geo-bore/"
      },
      {
        title: "Aspen School District Digs Deep For Clean Geothermal Energy",
        publisher: "The Colorado Sun",
        url: "https://coloradosun.com/2026/08/11/aspen-schools-geothermal-deep-bore-hold-1000-feet/"
      }
    ],
    image: "/images/projects/aspen.webp",
    imageAlt: "Vibrant summer landscape of the Maroon Bells mountains near Aspen, Colorado, featuring snow-capped peaks, a clear turquoise alpine lake, a lush green meadow filled with yellow wildflowers, and a bright blue sky with fluffy white clouds.",
    featured: true
  },
  {
    slug: "vail",
    name: "Vail",
    location: "Vail, CO",
    country: "United States",
    sqFeet: "593,000",
    buildings: "5",
    completion: "In Progress",
    status: "In Progress",
    summary: "Discover how Vail is reimagining one of the nation’s largest snowmelt systems through innovative district energy planning that reduces emissions, improves resilience, and creates a roadmap for future growth.",
    description: "The Vail project focuses on transforming one of the community’s largest energy users into a more sustainable thermal infrastructure asset in Vail, Colorado. The study area includes approximately 593,000 square feet of municipal and privately connected snowmelt systems serving Vail Village, Lionshead, and the Civic Hub. These systems are critical to winter mobility, safety, and visitor experience. GreyEdge evaluated how an Ambient Temperature Loop could reduce dependence on conventional heating fuels while preserving reliability. The project establishes a framework for long-term decarbonization of high-demand snowmelt infrastructure. It also creates opportunities for future connections to additional public and private facilities. Thermal assets evaluated include wastewater and reclaimed-water resources, geoexchange opportunities, groundwater sources, ice-rink heat recovery, and snowmaking-related infrastructure. Project findings suggest emissions could be reduced by a factor of five or more relative to existing conditions. The project demonstrates how mountain communities can leverage multiple thermal resources through a district-energy approach.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "McKinstry", url: "https://www.mckinstry.com/" },
      { name: "Martin & Martin", url: "https://www.martinmartin.com/" },
      { name: "Town of Vail", url: "https://www.vail.gov/" },
      { name: "Vail Resort", url: "https://www.vail.com/" },
      { name: "Eagle River Water and Sanitation District", url: "https://www.erwsd.org/" },
    ],
    articles: [
      {
        title: "Carbondale Geothermal Project",
        publisher: "thirdstreetcenter.net",
        url: "https://thirdstreetcenter.net/carbondale-geothermal-project/"
      }
    ],
    image: "/images/projects/vail.webp",
    imageAlt: "Aerial view of Vail, Colorado, showing alpine‑style buildings, pedestrian areas, and surrounding forested mountains in a green summer landscape.",
    featured: true
  },
  {
    slug: "steamboat-springs",
    name: "Steamboat Springs",
    location: "Steamboat Springs, CO",
    country: "United States",
    sqFeet: "2,162,531",
    buildings: "20",
    completion: "In Progress",
    status: "In Progress",
    summary: "Explore how renewable energy resources and innovative district planning could help power the future of one of Colorado’s premier mountain destinations.",
    description: "The Steamboat Springs project evaluates a Thermal Energy Network centered around the Gondola Transit Center and surrounding development areas in Steamboat Springs, Colorado. The study includes public facilities, resort infrastructure, future development, and snowmelt systems. GreyEdge assessed how a shared thermal network could meet significant heating demands in a challenging mountain climate. The project is designed to support growth while reducing long-term emissions and energy costs. A phased Ambient Temperature Loop approach allows multiple resources to work together within a unified system. This strategy creates a scalable foundation for future expansion. Thermal assets include geoexchange borefields, Yampa River heat exchange, snowmelt solar collection, wastewater energy recovery, solar thermal resources, and existing boilers for peak demand service. Project analysis identified the potential for approximately 85 percent reductions in heating-related carbon emissions. Prior evaluations estimated annual reductions of roughly 7,191 metric tons of CO2 under a fully renewable scenario. The project focuses on reducing borefield requirements while maximizing renewable resource opportunities. Steamboat Springs illustrates how mountain resort communities can integrate diverse thermal assets into a cohesive energy strategy.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "City of Steamboat Springs", url: "https://steamboatsprings.net/" },
      { name: "Steamboat Springs Redevelopment Authority (SSRA)" },
      { name: "Steamboat Ski & Resort Corporation (SSRC)", url: "https://www.steamboat.com/" },
      { name: "McKinstry", url: "https://www.mckinstry.com/" },
      { name: "Landmark Consultants" },
      { name: "Mount Werner Water", url: "https://www.mwwater.com/" },
      { name: "Bertram Drilling", url: "https://bertramdrilling.com/" },
      { name: "Zeven Element Design Institute" },
    ],
    articles: [],
    image: "/images/projects/steamboat-springs.webp",
    imageAlt: "A mountain town at the base of snow‑covered ski slopes in Steamboat Springs, Colorado, showing residential and resort buildings surrounded by green hills and peaks.",
    featured: true
  },
  {
    slug: "32-zed-zero-energy-district",
    name: "32 ZED – Zero Energy District",
    location: "Carbondale, CO",
    country: "United States",
    sqFeet: "164,490",
    buildings: "43",
    completion: "In Progress",
    status: "In Progress",
    summary: "Learn how a small mountain community is creating a replicable model for sustainable district energy and community-scale decarbonization.",
    description: "The Carbondale 32ZED project is a community-scale Thermal Energy Network designed to support a zero-energy district in Carbondale, Colorado. The district includes 43 buildings consisting of townhomes, a school, a library, offices, affordable housing, and community-serving facilities. The project area encompasses approximately 164,490 square feet of mixed-use development. GreyEdge serves as the technical lead supporting a phased transition away from conventional fossil-fuel heating. The initiative demonstrates how district energy can support affordability, sustainability, and economic resilience. The project establishes a replicable model for small communities pursuing decarbonization goals. Thermal assets include geo-connected infrastructure, water-source heat pumps, vertical and horizontal exchange fields, photovoltaic systems, and potential battery storage. The broader effort has been described as part of a $13 million initiative, with $700,000 in federal funding supporting investigation and design activities. Initial deployment targets approximately 25 percent of district heating and cooling demand with future expansion toward full district service. Project analysis identified the potential to eliminate approximately 3.2 billion Btu of natural gas consumption annually. The project demonstrates how Ambient Temperature Loop technologies can advance community-scale energy transformation.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Clean Energy Economy for the Region (CLEER)", url: "https://www.cleanenergyeconomy.net/" },
      { name: "Town of Carbondale", url: "https://www.carbondalegov.org/" },
      { name: "National Renewable Energy Laboratory (NREL)", url: "https://www.nrel.gov/" },
      { name: "Third Street Center", url: "https://thirdstreetcenter.net/" },
      { name: "Colorado Mountain College", url: "https://coloradomtn.edu/" },
      { name: "U.S. Department of Energy (DOE)", url: "https://www.energy.gov/" },
    ],
    articles: [
      {
        title: "Vail Colorado Explores Geothermal Heating For Snowmelt System",
        publisher: "thinkgeoenergy.com",
        url: "https://www.thinkgeoenergy.com/vail-colorado-explores-geothermal-heating-for-snowmelt-system/"
      }
    ],
    image: "/images/projects/32-zed-zero-energy-district.webp",
    imageAlt: "32 ZED Project Site Picture",
    featured: false
  },
  {
    slug: "breckenridge",
    name: "Breckenridge",
    location: "Breckenridge, CO",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "In Progress",
    status: "In Progress",
    summary: "Learn how Breckenridge is laying the groundwork for a scalable thermal energy network designed to support sustainability, resilience, and future development.",
    description: "The Breckenridge project evaluates a community-scale Ambient Temperature Loop for one of Colorado’s premier mountain communities. Initial planning identified Town Hall, the Professional Building, the Parking Structure, the Transit Center, and City Market as potential anchor facilities. Additional future housing and community assets are also being considered for connection. The project focuses on creating a resilient energy platform capable of supporting future growth. GreyEdge is using a phased planning approach to evaluate routing, loads, and implementation strategies. This effort provides a roadmap for long-term municipal decarbonization. Thermal assets include CLAD systems, vertical geothermal bores, wastewater energy recovery, freshwater heat recovery, mine-water resources, solar thermal systems, and snowmelt heat collection. These resources are intended to reduce borefield requirements and improve overall system economics. The project is focused on replacing fossil fuel demand with renewable thermal resources. Breckenridge demonstrates how thermal asset diversity can support future district-energy development.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Breckenridge", url: "https://www.townofbreckenridge.com/" },
      { name: "Colorado Energy Office (CEO)", url: "https://energyoffice.colorado.gov/" },
      { name: "Xcel Energy", url: "https://www.xcelenergy.com/" },
      { name: "CanAmerica Drilling", url: "https://canamericadrilling.com/" },
      { name: "Geothermal Resource Technologies Inc. (GRTI)", url: "https://www.grti.com/" },
      { name: "Bertram Drilling", url: "https://bertramdrilling.com/" },
      { name: "Vail Resorts / Breckenridge Ski Resort", url: "https://www.vailresorts.com/" },
    ],
    articles: [
      {
        title: "Breckenridge Eyes Proposal For An Energy Network That Could Take Some Town Owned Facilities Off The Natural Gas Pipeline",
        publisher: "Summit Daily",
        url: "https://www.summitdaily.com/news/breckenridge-eyes-proposal-for-an-energy-network-that-could-take-some-town-owned-facilities-off-the-natural-gas-pipeline/"
      }
    ],
    image: "/images/projects/breckenridge.jpeg",
    imageAlt: "A scenic view looking down a mountain town main street lined with historic brick and wooden buildings under a bright sky, leading toward towering alpine peaks and rocky cliffs in the background.",
    featured: false
  },
  {
    slug: "colorado-mesa",
    name: "Colorado Mesa University",
    location: "Grand Junction, CO",
    country: "United States",
    sqFeet: "1,600,000",
    buildings: "19",
    completion: "Operational / Phased Expansion",
    status: "Operational",
    summary: "See how Colorado Mesa University became a leading example of campus energy innovation through a phased geothermal and thermal network strategy.",
    description: [
      "Colorado Mesa University is a proven campus-scale Thermal Energy Network in Grand Junction, Colorado. Members of The GreyEdge Group, Cary Smith and Mark Smith, helped develop and implement the system, bringing firsthand experience that continues to inform our work today. The operational system serves approximately 19 academic, administrative, and student facilities across a 1.6 million-square-foot campus. A shared Ambient Temperature Loop enables buildings to exchange thermal energy and improve overall efficiency. The project demonstrates how phased implementation can support ongoing campus growth. GreyEdge considers CMU a leading precedent for higher-education thermal infrastructure. The network provides measurable operational and environmental benefits while improving resiliency.",
      "Thermal assets include seven geoexchange fields, an irrigation-water heat exchanger, ground-loop heat pumps, cooling towers, and backup boilers. The system capacity is approximately 4,700 tons. Since 2008, the Thermal Energy Network has saved CMU more than $16 million in avoided utility costs, including approximately $2 million in 2024 alone, and it avoids more than 18,000 metric tons of CO₂e each year. Those savings allowed the university to lower tuition by 2%. CMU demonstrates how an Ambient Temperature Loop can deliver scalable performance at the campus level.",
    ],
    team: [
      { name: "Sound Geothermal", url: "https://www.soundgt.com/" },
      { name: "Bighorn Engineering", url: "https://bighorneng.com/" },
      { name: "Colorado Mesa University", url: "https://www.coloradomesa.edu/" },
      { name: "McKinstry", url: "https://www.mckinstry.com/" },
    ],
    articles: [
      {
        title: "Networked Geothermal: The National Picture",
        publisher: "HEET",
        url: "https://www.heet.org/blog-items/networked-geothermal-the-national-picture",
      },
      {
        title: "Geo-Grid System",
        publisher: "Colorado Mesa University",
        url: "https://www.coloradomesa.edu/sustainability/initiatives/geo-grid.html",
      },
      {
        title: "Geothermal Heat Pump Case Study: Colorado Mesa University",
        publisher: "U.S. Department of Energy",
        url: "https://www.energy.gov/hgeo/geothermal/geothermal-heat-pump-case-study-colorado-mesa-university",
      },
      {
        title: "Colorado Mesa University Has Proven Geothermal Energy Can Largely Replace Fossil Fuels in Its Buildings. Now the World Is Taking Notice",
        publisher: "CPR News",
        url: "https://www.cpr.org/2025/04/23/colorado-mesa-university-geothermal-energy-use/",
      },
      {
        title: "Cmu Geothermal Expansion Builds Million Energy Savings",
        publisher: "kkco11news.com",
        url: "https://www.kkco11news.com/2026/02/19/cmu-geothermal-expansion-builds-12-million-energy-savings/",
      },
    ],
    image: "/images/projects/colorado-mesa.webp",
    imageAlt: "Colorado Mesa Project Site Picture",
    featured: false
  },
  {
    slug: "crested-butte",
    name: "Crested Butte",
    location: "Crested Butte, CO",
    country: "United States",
    sqFeet: "50,545",
    buildings: "8",
    completion: "In Progress",
    status: "In Progress",
    summary: "Discover how Crested Butte is leveraging local energy resources to create a resilient and scalable framework for community energy planning.",
    description: "The Crested Butte project evaluates municipal Thermal Energy Networks serving public facilities in Crested Butte, Colorado. The initial wastewater treatment district includes eight buildings totaling approximately 50,545 square feet. The project focuses on creating resilient infrastructure using locally available energy resources. The GreyEdge Group assessed opportunities to reduce energy consumption while supporting future district expansion. The study demonstrates how municipal facilities can benefit from shared thermal infrastructure. Thermal assets include wastewater effluent heat recovery, biofiltration heat exchange, geoexchange boreholes, solar thermal technologies, and existing boilers as peaking resources. The wastewater treatment district has an estimated peak heating load of approximately 230 tons. Analysis indicated that a hybrid Ambient Temperature Loop could reduce capital costs by approximately 39 percent, representing roughly $2.7 million in savings versus a geoexchange-only system. Energy consumption compared to current infrastructure is estimated to be reduced by approximately 87 percent. The project highlights how wastewater resources can become valuable thermal assets for municipal energy planning.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Crested Butte", url: "https://www.crestedbutte-co.gov/" },
    ],
    articles: [],
    image: "/images/projects/crested-butte.jpeg",
    imageAlt: "Vibrant yellow and orange calendula flowers bloom in sharp focus in the foreground, with the historic colorful storefronts of downtown Crested Butte, Colorado, and the massive, snow-dusted peak of Crested Butte mountain blurred beautifully in the background under a clear blue sky.",
    featured: false
  },
  {
    slug: "park-city",
    name: "Park City",
    location: "Park City, UT",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "In Progress",
    status: "In Progress",
    summary: "See how Park City is evaluating shared energy infrastructure to support redevelopment, strengthen sustainability goals, and create a flexible framework for long-term community growth.",
    description: "The Park City project evaluates district-scale Thermal Energy Networks across key redevelopment areas including Bonanza Park in Park City, Utah. The study includes public facilities, private development opportunities, and future mixed-use construction. The GreyEdge Group assessed how shared infrastructure could support long-term redevelopment and sustainability goals. Planning identified opportunities for district energy systems that can grow alongside future development. The project provides a framework for community-scale electrification and resilient energy infrastructure. Thermal assets considered include wastewater energy recovery, mine-water resources, solar thermal systems, CLAD technology, vertical boreholes, groundwater infrastructure, snowmelt solar collection, and surface-water opportunities. The study is focused on identifying the most viable pathways for an Ambient Temperature Loop. The diverse portfolio of thermal resources provides significant flexibility for future implementation. Park City demonstrates how district-energy planning can be integrated into community redevelopment strategies.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Park City Municipal Corporation", url: "https://www.parkcity.org/" },
      { name: "Cairn Global" },
      { name: "Snyderville Basin Water Reclamation District", url: "https://www.sbwrd-ut.gov/" },
      { name: "Utah Department of Natural Resources", url: "https://naturalresources.utah.gov/" },
    ],
    articles: [
      {
        title: "Park City Explores Thermal Technology As Energy Efficiency Tool",
        publisher: "KPCW",
        url: "https://www.kpcw.org/park-city/2026-08-05/park-city-explores-thermal-technology-as-energy-efficiency-tool"
      }
    ],
    image: "/images/projects/park-city.webp",
    imageAlt: "Elevated wide-angle view of historic downtown Park City, Utah, at dusk, showing illuminated buildings, streets, and parking areas nestled in a mountain valley surrounded by lush green slopes and forested hillsides under a twilight sky.",
    featured: false
  },
  {
    slug: "telluride",
    name: "Telluride",
    location: "Telluride, CO",
    country: "United States",
    sqFeet: "20,000",
    buildings: "8",
    completion: "In Progress",
    status: "In Progress",
    summary: "Discover how Telluride is combining housing, infrastructure, and clean energy planning to support long-term community goals and environmental leadership",
    description: "The Telluride project supports affordable housing, transit, commercial development, and municipal infrastructure in Telluride, Colorado. The development program includes approximately 265 housing units, 20,000 square feet of commercial space, parking facilities, childcare, and public-service infrastructure. Planned facilities include mixed-use developments at Lot L and Carhenge along with public works and transit assets. By integrating these uses into a shared Thermal Energy Network, the Town can support growth without relying on conventional heating approaches. The project aligns housing, transportation, and sustainability objectives within a single infrastructure strategy. GreyEdge identified a strong opportunity for district energy implementation in this rapidly evolving area. Thermal assets evaluated include wastewater energy recovery, energy piles, vertical boreholes, Genesys CLAD technology, solar thermal systems, snowmelt collection, and mine-water resources. Project studies identified an estimated 1,000-ton heating load excluding snowmelt energy. Modeling indicated a potential greenhouse gas reduction of approximately 53 percent compared with a natural gas boiler baseline. The Ambient Temperature Loop concept provides flexibility for future community expansion and redevelopment. The project illustrates how shared infrastructure can support climate goals while addressing community housing needs.",
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Telluride", url: "https://www.telluride.gov/" },
      { name: "Colorado Energy Office (CEO)", url: "https://energyoffice.colorado.gov/" },
    ],
    articles: [],
    image: "/images/projects/telluride.webp",
    imageAlt: "Looking down historic Colorado Avenue in downtown Telluride, Colorado, lined with historic brick and wooden buildings flying Colorado and US flags, leading the eye toward a massive mountain box canyon with green slopes, rocky cliffs, and a waterfall under a bright sky.",
    featured: false
  },
  {
    slug: "pitkin-county",
    name: "Pitkin County",
    location: "Aspen, CO",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "In Progress",
    status: "In Progress",
    summary: "See how Pitkin County Airport is evaluating geothermal and Ambient Temperature Loop opportunities to support long-term electrification, resiliency, and sustainability in Aspen’s alpine environment.",
    description: [
      "Pitkin County Airport represents a forward-looking infrastructure planning effort focused on evaluating geothermal and Ambient Temperature Loop (ATL) opportunities as part of the airport's long-term energy and sustainability strategy in Aspen, Colorado. The project evaluated how geothermal infrastructure could support future electrification, improve energy performance, and reduce dependence on conventional heating systems. The study explored opportunities to integrate airport facilities with a shared thermal infrastructure approach capable of supporting reliable year-round operation in a demanding alpine environment. By assessing district-scale energy solutions early in the planning process, Pitkin County gained a clearer understanding of how geothermal resources could support long-term resiliency, operational efficiency, and carbon reduction objectives. The project highlights how critical transportation infrastructure can leverage geothermal energy to support both sustainability goals and future growth.",
      "The Thermal Assets evaluated included geoexchange borefields and other local thermal resources capable of supporting an Ambient Temperature Loop architecture. The study examined how heat pump technologies, thermal storage strategies, and interconnected geothermal infrastructure could improve system efficiency while reducing emissions and future energy costs. The assessment focused on identifying practical pathways for electrification that align with the operational requirements of an active regional airport. The Ambient Temperature Loop concept provides flexibility for future facility improvements and expansion while supporting long-term sustainability objectives. The project illustrates how geothermal planning can help public infrastructure transition toward more resilient, low-carbon energy systems over time.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Pitkin County, Aspen/Pitkin County Airport", url: "https://www.aspenairport.com/" },
      { name: "Pitkin County Public Works", url: "https://www.pitkincounty.com/304/Public-Works" },
      { name: "Roaring Fork Transportation Authority", url: "https://www.rfta.com/" },
      { name: "Holy Cross Energy", url: "https://www.holycross.com/" },
      { name: "Colorado Energy Office", url: "https://energyoffice.colorado.gov/" },
    ],
    articles: [],
    image: "/images/projects/pitkin-county.jpg",
    imageAlt: "Autumn landscape near Aspen, Colorado, showing earth-toned residential buildings nestled among golden aspen and evergreen trees at the base of a sunlit hillside under a clear blue sky, with a manicured green in the foreground.",
    featured: false
  },
  {
    slug: "winter-park",
    name: "Winter Park",
    location: "Winter Park, CO",
    country: "United States",
    sqFeet: "117,000+",
    buildings: "3",
    completion: "Phase 2 Feasibility",
    status: "In Progress",
    summary: "Discover how Winter Park is advancing a community-scale Thermal Energy Network to support growth, electrification, and emissions reduction across mixed-use and municipal facilities.",
    description: [
      "Winter Park represents a community-scale energy planning effort focused on developing a Thermal Energy Network that can support long-term growth, electrification, and emissions reduction in Winter Park, Colorado. The project is currently advancing through Phase 2 feasibility studies and includes multiple mixed-use and municipal facilities, including Copper Creek Square, Viking Lodge, and the Town Hall and Utilities complex. Together, these buildings account for more than 117,000 square feet of conditioned space, along with approximately 12,000 square feet of snowmelt infrastructure. By connecting these facilities through a shared Thermal Energy Network, the Town can reduce reliance on conventional heating systems while creating a scalable energy platform capable of supporting future expansion. The project demonstrates how district-scale energy infrastructure can align community development, resiliency, and sustainability goals within a single long-term strategy.",
      "The Thermal Assets evaluated include geothermal borefields, municipal water and wastewater heat recovery, solar thermal collection, surface-water integration, and water-to-water heat pump systems. A 500-foot geothermal test borehole was successfully drilled, logged, and thermally tested, confirming favorable subsurface conditions and supporting continued system development. Project studies identified a total system capacity of approximately 450 refrigeration tons, equivalent to 5.3 MMBtu of heating, cooling, and snowmelt demand. Modeling indicates the Thermal Energy Network could reduce greenhouse gas emissions by more than 70 percent compared with conventional energy systems while creating a flexible framework for future growth. The project illustrates how shared thermal infrastructure can help mountain communities achieve ambitious climate goals while providing reliable and efficient energy for years to come.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Clean Energy Economy for the Region (CLEER)", url: "https://www.cleanenergyeconomy.net/" },
      { name: "Bighorn Engineering", url: "https://bighorneng.com/" },
      { name: "National Renewable Energy Laboratory (NREL)", url: "https://www.nrel.gov/" },
    ],
    articles: [],
    image: "/images/projects/winter-park.jpg",
    imageAlt: "Sunset over Winter Park, Colorado, with snow-dusted evergreen mountains, a winding road leading to lodge and municipal buildings in the valley, and warm orange and pink light across the sky.",
    featured: false
  },
  {
    slug: "mountain-village",
    name: "Mountain Village",
    location: "Mountain Village, CO",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "Phase 1 Evaluation",
    status: "In Progress",
    summary: "See how Mountain Village is evaluating geothermal infrastructure and an Ambient Temperature Loop to support long-term sustainability, resiliency, and district energy goals.",
    description: [
      "Mountain Village represents a community-scale planning effort focused on evaluating how geothermal infrastructure and an Ambient Temperature Loop could support long-term sustainability, resiliency, and district energy objectives in Mountain Village, Colorado. The Phase 1 evaluation study examined the potential for a Thermal Energy Network to serve existing and future development through a shared energy infrastructure approach. By exploring district-scale solutions early in the planning process, the community gained a clearer understanding of how geothermal resources could reduce reliance on conventional heating systems while supporting future growth. The project highlights how mountain communities can evaluate shared thermal infrastructure as part of a broader strategy for energy efficiency, electrification, and greenhouse gas reduction.",
      "The Thermal Assets evaluated included geothermal and Ambient Temperature Loop opportunities capable of supporting a connected district energy system. The study focused on identifying resources and infrastructure strategies that could improve energy performance, increase system flexibility, and create a foundation for future expansion. Through early-stage technical evaluation, the project explored how shared thermal infrastructure could support the community's long-term sustainability and resilience goals. The Ambient Temperature Loop concept provides a framework for future development while creating opportunities to reduce emissions and improve overall system efficiency. The project illustrates how geothermal planning can help mountain communities align growth, infrastructure investment, and climate objectives within a single long-term strategy.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Mountain Village Community Development", url: "https://townofmountainvillage.com/" },
      { name: "Town of Mountain Village Public Works", url: "https://townofmountainvillage.com/" },
      { name: "Colorado Energy Office", url: "https://energyoffice.colorado.gov/" },
    ],
    articles: [],
    image: "/images/projects/mountain-village.jpg",
    imageAlt: "Aerial autumn view of Mountain Village, Colorado, nestled in a deep alpine valley amid golden aspen and evergreen slopes, with snow-dusted peaks under a clear blue sky.",
    featured: false
  },
  {
    slug: "lexington",
    name: "Lexington",
    location: "Lexington, MA",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "HEET Evaluation Study",
    status: "Completed",
    summary: "See how Lexington evaluated geothermal infrastructure and Ambient Temperature Loop technology as a pathway for long-term community decarbonization.",
    description: [
      "Lexington represents an early-stage community energy planning effort focused on evaluating the potential for geothermal infrastructure and Ambient Temperature Loop technology to support long-term decarbonization goals in Lexington, Massachusetts. The project was conducted as a HEET-funded evaluation study to assess how a Thermal Energy Network could leverage local thermal resources and shared infrastructure to reduce reliance on conventional heating systems. By exploring district-scale energy opportunities, the study helped identify pathways for electrification, energy efficiency, and greenhouse gas reduction that could support future community needs. The project highlights how municipalities can use geothermal feasibility studies to better understand local energy opportunities and establish a framework for future Thermal Energy Network development.",
      "The Thermal Assets evaluated as part of the study were analyzed to determine their potential to support an Ambient Temperature Loop and future district energy infrastructure. The assessment focused on identifying practical opportunities to improve energy performance, increase system flexibility, and support long-term community sustainability objectives. Through early-stage technical evaluation, the project examined how shared thermal infrastructure could provide a scalable foundation for future electrification efforts. The Ambient Temperature Loop concept offers a pathway for integrating multiple energy resources into a unified system capable of supporting future growth and decarbonization initiatives. The project illustrates how geothermal planning can help communities align infrastructure investments with long-term climate and energy goals.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Lexington", url: "https://www.lexingtonma.gov/" },
      { name: "BR+A", url: "https://www.brplusa.com/" },
      { name: "HEET", url: "https://www.heet.org/" },
      { name: "Massachusetts Clean Energy Center (MassCEC)", url: "https://www.masscec.com/" },
    ],
    articles: [],
    image: "/images/projects/lexington.jpg",
    imageAlt: "Aerial autumn view of Lexington Battle Green in Lexington, Massachusetts, showing the historic common, white First Parish steeple, surrounding New England homes, and vibrant fall foliage under a clear blue sky.",
    featured: false
  },
  {
    slug: "fraser",
    name: "Fraser",
    location: "Fraser, CO",
    country: "United States",
    sqFeet: null,
    buildings: null,
    completion: "Study Complete",
    status: "Completed",
    summary: "Explore how Fraser evaluated a geothermal heating district for planned Town-owned developments—and what the analysis revealed about local thermal resources and future potential.",
    description: [
      "Fraser represents a community-scale geothermal planning effort focused on evaluating district energy opportunities that could support future development, energy resilience, and emissions reduction in Fraser, Colorado. The project evaluated a potential geothermal heating district serving two planned developments on Town-owned property: Victoria Village and Clayton Court. By connecting these developments through a shared Thermal Energy Network, the Town could leverage local thermal resources to reduce reliance on conventional heating systems while supporting long-term community growth. The study identified a strong opportunity for district energy implementation by integrating multiple thermal assets unique to the site into a single infrastructure strategy. Although the project ultimately did not advance due to development schedule conflicts, the analysis demonstrated significant potential for a future geothermal heating district.",
      "The Thermal Assets evaluated included wastewater treatment plant effluent, shallow geothermal ground heat exchangers, and the Town's raw water distribution system. Project studies identified several promising thermal resources capable of supporting a shared heating network and improving overall system efficiency. The evaluation demonstrated that Fraser possesses the core infrastructure elements needed for a high-performing geothermal district energy system capable of serving future community development. The Thermal Energy Network concept provides a flexible framework for future expansion while reducing dependence on traditional fossil-fuel-based heating systems. The project illustrates how local energy resources can be integrated into a shared infrastructure approach that supports both sustainability objectives and community growth.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Town of Fraser", url: "https://www.frasercolorado.com/" },
      { name: "Mountain Affordable Housing Development" },
      { name: "Vogel & Associates", url: "https://www.vogelassoc.com/" },
      { name: "ESA", url: "https://www.esapc.com/" },
      { name: "JVA", url: "https://www.jvajva.com/" },
    ],
    articles: [],
    image: "/images/projects/fraser.jpg",
    imageAlt: "Main street in Fraser, Colorado, looking toward snow-capped mountains, with wooden storefronts, parked vehicles, and patches of snow under a clear blue sky.",
    featured: false
  },
  {
    slug: "hayden",
    name: "Hayden",
    location: "Hayden, CO",
    country: "United States",
    sqFeet: null,
    buildings: "1",
    completion: "In Progress",
    status: "In Progress",
    summary: "See how the Hayden Center is replacing conventional heating with an integrated geothermal HVAC system that supports town sustainability goals and long-term facility performance.",
    description: [
      "The Hayden Center Geothermal System project supports the modernization of a key public facility in Hayden, Colorado through the replacement of conventional heating infrastructure with a geothermal-based system. The project focuses on evaluating, designing, and implementing an integrated geothermal HVAC solution that aligns with the Town's sustainability objectives while maintaining reliable operation of an important community asset. The design approach considers both the building systems and underground geothermal infrastructure as a single coordinated heating and cooling solution rather than separate systems. Through a collaborative process involving the Town of Hayden and a multidisciplinary engineering team, the project is intended to reduce reliance on conventional energy sources while providing long-term operational value and improved facility performance.",
      "The Thermal Assets evaluated include geothermal borefields, ground loop heat exchanger infrastructure, heat pump technology, thermal storage opportunities, and the integration of multiple thermal sources and sinks capable of supporting high-efficiency operation. The project includes detailed hydrogeologic review, energy modeling, borefield design, control system integration, and commissioning strategies to ensure long-term performance. Particular emphasis was placed on optimizing borefield sizing, thermal exchange capacity, system controls, and future flexibility so the geothermal infrastructure can continue serving the facility as operational needs evolve. The project illustrates how public facilities can leverage geothermal infrastructure to improve efficiency, support decarbonization goals, and create a foundation for long-term sustainable operation.",
    ],
    team: [
      { name: "The GreyEdge Group", url: "/" },
      { name: "Bighorn Consulting Engineers", url: "https://bighorneng.com/" },
      { name: "Landmark Consultants" },
      { name: "Steamboat Engineering and Design" },
      { name: "Town of Hayden", url: "https://www.haydencolorado.com/" },
    ],
    articles: [],
    image: "/images/projects/hayden.jpg",
    imageAlt: "Dirt road winding through golden aspens and snow-dusted evergreens toward rugged, snow-capped peaks under a clear blue sky near Hayden, Colorado.",
    featured: false
  },
  {
    slug: "weber-state-university",
    name: "Weber State University",
    location: "Ogden, UT",
    country: "United States",
    sqFeet: "3,273,915",
    buildings: "31",
    completion: "Operational / Phased Expansion 2040",
    status: "Operational",
    summary: "Explore how Weber State University is transforming a traditional campus district energy system into a multi-source Thermal Energy Network, leveraging geothermal resources, electrification, and infrastructure to improve efficiency, resilience, sustainability.",
    description: [
      "Weber State University represents a large-scale campus modernization effort centered on electrification and geothermal infrastructure in Ogden, Utah. Members of The GreyEdge Group, Cary Smith and Mark Smith, played key roles in advancing the geothermal and energy-transition strategies that helped shape the University's long-term infrastructure vision. The project encompasses approximately 31 academic, administrative, and support buildings totaling 3.27 million square feet. Planning efforts evaluated how geothermal resources could support campus-wide decarbonization, improve energy performance, and reduce reliance on conventional heating systems. Through a phased implementation approach, the University has been able to modernize critical infrastructure while maintaining reliable building operations. The project serves as a leading example of how higher education institutions can transition toward resilient, all-electric energy systems over time.",
      "Thermal assets include campus geothermal fields, building electrification measures, and interconnected thermal infrastructure designed to support long-term sustainability goals. The project has resulted in a significant reduction in annual energy consumption, with campus energy use intensity decreasing from 125 kBtu/sf/yr to 60 kBtu/sf/yr. Over a 15-year period, the system retrofit has demonstrated approximately 50 percent utility cost savings. Weber State University highlights the long-term value of integrating geothermal infrastructure into a phased campus modernization strategy, while showcasing the type of transformational work that informs The GreyEdge Group's approach to higher-education energy systems today.",
    ],
    team: [
      { name: "Weber State University", url: "https://www.weber.edu/" },
      { name: "Sound Geothermal", url: "https://www.soundgt.com/" },
    ],
    articles: [
      {
        title: "WSU's Climate Action Plan & Energy Strategy",
        publisher: "Weber State University",
        url: "https://www.weber.edu/sustainability/energy.html",
      },
      {
        title: "Networked Geothermal: The National Picture",
        publisher: "HEET",
        url: "https://www.heet.org/blog-items/networked-geothermal-the-national-picture",
      },
      {
        title: "Geothermal Wells Deepen Weber State's Sustainability Efforts",
        publisher: "Standard-Examiner",
        url: "https://www.standard.net/news/environment/2016/may/29/geothermal-wells-deepen-weber-states-sustainability-efforts/",
      },
    ],
    image: "/images/projects/weber-state-university.webp",
    imageAlt: "Weber State University Campus Project Picture",
    featured: false
  }
]

export const featuredProjects = projects.filter((p) => p.featured)

export const getProject = (slug: string) => projects.find((p) => p.slug === slug)
