export interface TeamMember {
  slug: string
  name: string
  role: string
  credentials: string | null
  email: string | null
  phone: string | null
  website: string | null
  linkedin: string | null
  /** Background — prose paragraphs. */
  bio: string[]
  /** Areas of Expertise — prose paragraphs. */
  expertise: string[]
  /** Notable Projects & Achievements — bullet items. */
  achievements: string[]
  image: string | null
  imageAlt: string
  leadership: boolean
}

/** Grid order from the legacy Our Team page (5-across). */
export const teamOrder = [
  'matthew-garlick',
  'richard-b-white',
  'cary-smith',
  'paul-bony',
  'garen-ewbank',
  'stephen-hamstra',
  'john-mclennan',
  'bill-odonnell',
  'roshan-revankar',
  'garry-sexton',
  'mark-smith',
  'jaiden-marriott',
  'megan-lim',
  'delaini-moss-marriott',
  'ian-talbot',
] as const

export const team: TeamMember[] = [
  {
    slug: 'matthew-garlick',
    name: 'Matthew Garlick',
    role: 'CEO',
    credentials: 'CEM, CCP, BEMP',
    email: 'mgarlick@greyedgegroup.com',
    phone: null,
    website: null,
    linkedin: 'https://www.linkedin.com/in/matt-garlick-ccp-cem-bemp-585a2833/',
    bio: [
      'Matt Garlick is a man who loves what he does! Although he took a non-traditional route to get where he is, he has found a place to put his talents to good use and improve the world through efficient design. Matt holds a Master of Architecture degree from the University of Utah and is a Building Energy Modeling Professional, a Certified Energy Manager and a Certified Commissioning Professional.',
      'Matt is a leading advocate for Thermal Energy Networks and regularly speaks to professional organizations such as CAST, RMUE and MT2030. In an industry filled with engineers, Matt’s combination of a broad understanding and technical expertise allows him to reduce complicated ideas into simpler forms. This helps bridge the worlds of owners, architects, engineers and contractors and encourages efficient systems that deliver in the real world. Matt is a dedicated energy efficiency professional with a proven skill for technical leadership. As CEO of the GreyEdge Group, Matt is committed to delivering cost effective thermal decarbonization and sustainable comfort solutions.',
    ],
    expertise: [
      'Matt’s career has led to working on building typologies that have the most to gain from energy efficiency. He has developed energy models and provided design teams with actionable recommendations on over 12,000,000sf of projects from China to Canada and California to New York. Working as the lead commissioning agent, he has also led teams on over 1,000,000sf of projects and an additional 400,000sf of existing building retro-commissioning.',
    ],
    achievements: [
      'ATL Assessment and Design — Carbondale, CO',
      'ATL Assessment and Design — Vail, CO',
      'ATL Assessment — Lexington, MA',
      'Medina, Saudi Arabia ATL Load Modeling',
      'ATL Assessment — Breckenridge, CO',
      'ATL Assessment — Winter Park, CO',
      'ATL Assessment — Pitkin County Airport, CO',
      'ATL Assessment — Aspen School District, CO',
      'ATL Assessment — Mountain Village, CO',
      'ATL Assessment — Park City, UT',
      'ATL Assessment — Deer Valley Resort, UT',
      'WSU Noorda Engineering Building Geo and LEED Modeling — Ogden, Utah',
      'Lakeview Landing Modeling — Brewery, Restaurant, Residence District Heat Pump Modeling',
      '2023 BCxA 20 under 40 Awardee',
    ],
    image: '/images/team/matthew-garlick.webp',
    imageAlt: 'A Head Shot of Matthew Garlick who the CEO of The Grey Edge Group.',
    leadership: true,
  },
  {
    slug: 'richard-b-white',
    name: 'Richard B. White',
    role: 'Hydrogeologist',
    credentials: 'P.E.',
    email: 'rwhite@greyedgegroup.com',
    phone: '801-673-6647',
    website: 'http://www.rbwhitepe.com/',
    linkedin: null,
    bio: [
      'With over 45 years of consulting engineering practice, Rich has substantial experience in the assessment, design, and management of civil and environmental engineering projects. Through this experience, he has gained an in-depth understanding of the critical role that surface and subsurface water, soil, and rock play on project success. He has provided consulting engineering services to small and large mining, oil and gas, chemical, and other industrial concerns as well as local, State, and Federal governments throughout the United States and internationally. His designs have been implemented to restore natural conditions, mitigate past environmental impacts, prevent future impacts, allow aquifer storage and recovery of groundwater, and permit ground-source heat exchange.',
    ],
    expertise: [
      'Rich has extensive experience conducting hydrogeologic assessments to evaluate potential groundwater supplies and identify drilling challenges. His expertise includes assessing and mitigating environmental impacts associated with land development, as well as designing disturbed-land reclamation, runoff- and sediment-control, and stream channel stabilization plans. He also provides rapid engineering response to oil spills and other environmental emergencies and prepares comprehensive plans for the remediation of soil and groundwater contamination.',
    ],
    achievements: [
      'Conducted office and field evaluations of hydrogeologic conditions at multiple locations across the United States to aid in the design of open- and closed-loop ground-source heat exchange systems',
      'Served as senior water resources engineer on a project to evaluate and implement Aquifer Storage and Recovery for the community of Provo, Utah',
      'Prepared specifications and supervised the installation of multiple exploratory boreholes in Salt Lake County, Utah to develop a data-base for the design of large-quantity production wells',
      'Supervised environmental characterization efforts at rocket-motor production facilities, petroleum refineries, petroleum pipelines, printed-circuit facilities, abandoned smelter complexes, and other industrial facilities in the western and midwestern United States to determine the extent and magnitude of soil and groundwater contamination',
      'Conducted an investigation at the site of an active uranium mill in southeastern Utah to determine appropriate remedial actions to prevent future groundwater contamination after a plume had developed due to seepage from tailings ponds',
    ],
    image: '/images/team/richard-b-white.webp',
    imageAlt: 'A head shot of Richard B. White who is a Hydrogeologist at The Grey Edge Group',
    leadership: true,
  },
  {
    slug: 'cary-smith',
    name: 'Cary Smith',
    role: 'ATL Specialist',
    credentials: 'CGD, CEM, CEA, CGI, AEE Fellow',
    email: 'csmith@greyedgegroup.com',
    phone: '801-244-8800',
    website: 'https://www.soundgt.com/',
    linkedin: 'https://www.linkedin.com/in/cary-smith-cem-cea-cgd-cgi-aee-fellow-37b6a010/',
    bio: [
      'Cary worked as a Drilling Engineer and related fields in the Oil and Gas Industry from 1972 to 1997. During that time his specialty was advanced and high temperature drilling fluids and drilling optimization. Cary has worked in the GSHP industry since 1997 and has been involved in the design and implementation of over 80,000 tons (~280 MW) of installed capacity in North America. Cary is a founding member and acting CFO of the GreyEdge Group and an AEE Fellow.',
    ],
    expertise: [
      'Applying a “Systems” approach to networked geothermal design is a key to making systems function economically, correctly and with a minimum carbon footprint. This requires complete integration of the Ground Heat Exchanger (GHE), mechanical piping, and controls. As an early adopter of this approach, we have been able to integrate systems from several HUD homes to university campuses. Mixed use applications in city and Campus environments provide ideal opportunity to bring together wasted energy collection and re-use that energy, significantly increasing System Coefficient of Performance (SCOP). This approach not only increases efficiency but also dramatically reduces greenhouse gas emission and water consumption.',
    ],
    achievements: [
      'Cashman Equipment Henderson Facility, Cashman Equipment, Las Vegas, Nevada. ~500,000 ft² (LEED & Hybrid) 900 tons. Multi Building Community Loop',
      '250,000 ft², six-building Hospital Campus, Extended Care Facility, Doctors Clinics, Same Day Surgery, Emergency, Women’s OB Center — add community loop design to interconnect existing buildings with the main hospital and future buildings.',
      '2007–Present Mesa State College, Grand Junction Colorado. Design new classroom building, hybrid and borefield design. Development of Community Loop system for 4,700 connected tons, 16 buildings, 1.2MM ft².',
      'Co-author of, and teaches, the Certified Geothermal Inspector and Certified Geothermal Designer courses.',
      'International Association of Plumbing and Mechanical Officials (IAPMO) 2026, 2023, and 2020 Uniform Mechanical Code (UMC) Technical committees and the 2027, 2024, 2021, and 2018 Uniform Solar, Hydronics and Geothermal Code (USHGC) national code committees. He is past Chair of the 2024 USHGC code committee and is currently Chair of TSC Z1381, the Ambient Temperature Loop Standards Committee.',
      'Association of Energy Engineers Fellow',
    ],
    image: '/images/team/cary-smith.webp',
    imageAlt: 'A Head Shot of Cary Smith who is an ATL Specialist at The Grey Edge Group',
    leadership: true,
  },
  {
    slug: 'paul-bony',
    name: 'Paul Bony',
    role: 'Energy Professional',
    credentials: null,
    email: 'pbony@greyedgegroup.com',
    phone: '970-209-0999',
    website: null,
    linkedin: 'https://www.linkedin.com/in/paul-bony-5b363243/',
    bio: [
      'Accomplished professional with deep experience in the conditioned space, energy efficiency, utility, and clean energy industries. Results oriented nationally recognized expert with proven success establishing and developing high value relationships, programs, services and profit streams benefiting all stakeholders. A passionate leader in the product delivery, financing, utility and contractor development arenas. President of the Solar Energy International Board of Directors and a member of the International Ground Source Heat Pump Association Board of Directors.',
    ],
    expertise: [],
    achievements: [
      'Received EPA/DOE “Excellence in Energy Star Outreach” Award',
      'Awarded the Association of Energy Services Professionals “Achievement in Energy Services”',
      'Awarded the National Rural Electric Cooperative Association’s “Best Total Communications Program”',
      'Established ClimateMaster as the preferred partner in a major utility program and in a net zero military project',
      'Built the Nation’s first off-grid PV leasing program',
      'Created the first utility-owned renewable ground-source heat pump loop tariff',
      'Brought Carrier Corp to EGIA, resulting in revenues benefiting both firms in the U.S. and Canada',
      'Created and launched the national Home Energy Makeover Contest',
      'Hosted the first U.S. propane powered fuel cell outside of a laboratory, leading to the successful Plug Power IPO',
      'Founded and served as the Operations Manager of a HVAC company. Developed and implemented business plans and staffing, financial forecasts, marketing plans, pricing models, operating procedures and drove sales. Reached rapid profitability and exceeded revenue goals',
      'Managed business operations with annual billings in excess of $25 Million, over 40 employees and had responsibility for annual operating budgets up to $5 Million',
    ],
    image: '/images/team/paul-bony.webp',
    imageAlt: 'A Head Shot of Paul Bony',
    leadership: true,
  },
  {
    slug: 'garen-ewbank',
    name: 'Garen Ewbank',
    role: 'Thermal Conductivity Specialist',
    credentials: 'CEM, CEA, CGD, CGI',
    email: 'gewbank@greyedgegroup.com',
    phone: '405-826-8156',
    website: null,
    linkedin: 'https://www.linkedin.com/in/garen-ewbank-436a0b11/',
    bio: [
      'Garen grew up in the water well and oil and gas drilling industries. Garen’s motto is “keep turning to the right”. Garen has worked in the GSHP industry since 1979 and has been involved in the design and implementation of well over 100,000 MW (millions of feet) of installed heat pump equivalent capacity in North America. Garen was a contributor to several training courses to include the Certified GeoExchange Designer Course and Syllabus that has been adopted by the International Ground Source Heat Pump Association (IGSHPA) and the Association of Energy Engineers. Garen is a member of the Technical Committee to develop the Bi-National CSA/ANSI C448 Standard for the Design and Installation of Ground Source Heat Pumps for Commercial and Residential Buildings. Garen is a founding member of the GreyEdge Group.',
    ],
    expertise: [
      'Garen developed the in situ thermal conductivity testing methodology used by the GSHP industry to size and design ground heat exchangers (GHEX). Garen is co-owner of the patented Advanced Thermal Conductivity Method (ACTM) that shortens the testing duration and quantifies the diffusivity. Garen has installed GHEXs throughout the U.S. and consulted throughout the world on GHEXs. Garen has been a primary investigator/collaborator on numerous applied research projects on the GHEX, borehole resistance and thermal storage. Garen has peer reviewed several software applications to size and design the GHEX. Garen trains for IGSHPA in all courses domestically and internationally.',
    ],
    achievements: [
      'Pioneered in situ thermal conductivity testing for the ground source heat pump industry in 1994 and the ACTM in 2016.',
      'Developed re-circulating stiff foam drilling methods for lost circulation zones',
      'Researched ground, grout and piping heat transfer',
      'Consulted with state regulators and state drilling associations on GHEX regulations in many states',
      'Co-authored papers for ASHRAE on earth thermal properties, borehole resistance and piping configurations',
      'Holds patent pending on heat pumps and domestic and international design software; awarded several patents on drilling rigs and water pumping systems',
      'Awarded the grade of Fellow and received the Legends in Energy award with the Association of Energy Engineers',
      'Garen has trained thousands of individuals for IGSHPA in all courses',
      'Garen is a member of the Strategic Advisory Council for the College of Engineering, Architecture, and Technology (CEAT) at Oklahoma State University',
    ],
    image: '/images/team/garen-ewbank.webp',
    imageAlt: 'A Head Shot of Garen Ewbank.',
    leadership: true,
  },
  {
    slug: 'stephen-hamstra',
    name: 'Stephen Hamstra',
    role: 'Lead Engineer',
    credentials: 'PE, ASHRAE HBDP, Life Member, AEE Fellow, CGD, LEED AP',
    email: 'shamstra@greyedgegroup.com',
    phone: '616-566-6185',
    website: null,
    linkedin: 'https://www.linkedin.com/in/shamstra/',
    bio: [
      'Steve grew up in a family HVAC business, his father was an early-adopter of ground-source heat pump (GSHP) systems in the 1970’s. Steve has always had a passion for sustainability and renewable energy, building concentrating solar collectors while in high school and studying various high-performance building design approaches. He served for nearly 4 decades as a principal in an architecture & engineering firm, piloting the design of many energy efficient and innovative projects that included ground-source heat pumps, energy recovery, thermal energy storage, solar PV, etc.',
      'Steve is the Vice-Chair (soon to be Chair) of ASHRAE TC 6.8 Ground-Source Heat Pumps and Energy Recovery, and has designed many, many ground-source systems in his career. He developed and patented a web based GSHP design software, which would automatically export a self-learning control algorithm for large GSHP systems. This control approach has been installed on several military bases, universities and other applications.',
    ],
    expertise: [
      'Steve has several patented innovations in the HVAC marketplace and has enjoyed the design process as well as directing and managing many design professionals for several AE firms. In addition to his work at Melink Solar & Geo, and his efforts with The GreyEdge Group, he also has his own consulting practice; Zeven Element Design Institute (ZEDI PLC).',
    ],
    achievements: [
      'ASHRAE 2014 1st Place Global Award for the Low Energy Science Building designed for the University of Findlay. It includes a GSHP, DOAS and radiant heating/cooling.',
      'Several articles published in Engineered Systems Magazine: “V” is for Ventilation; “Large Scale Geothermal Heat Pump Systems”; “Pumping and Flow Controls in Geothermal Heat Pump Systems”',
      'Advisor to ASHRAE and Dr. Steve Kavanaugh on the design handbook; “Ground-Source Heat Pumps: Design of Geothermal Systems for Commercial and Institutional Buildings” published in 2013',
      'Speaker at dozens of ASHRAE, IGSHPA and various green building conferences since the 1990’s.',
      'Steve has served on numerous civic, community, and advisory boards as member and chair including City Council, Board of Education, Hospital Board, Municipal Utility Board and others.',
    ],
    image: '/images/team/stephen-hamstra.webp',
    imageAlt: 'A Head Shot of Steve Hamstra.',
    leadership: true,
  },
  {
    slug: 'john-mclennan',
    name: 'John McLennan',
    role: 'Advanced Geothermal Power Researcher',
    credentials: null,
    email: 'jmclennan@greyedgegroup.com',
    phone: '801-634-4412',
    website: 'https://faculty.utah.edu/u0607793-JOHN_DAVID_MCLENNAN/teaching/index.hml',
    linkedin: 'https://www.linkedin.com/in/john-mclennan-893383a/',
    bio: [
      'Since October 2009, Professor John McLennan has been a faculty member in the Department of Chemical Engineering at the University of Utah. He has been a Senior Research Scientist at the Energy & Geoscience Institute and an Adjunct Professor in the Department of Civil Engineering at the University of Utah since January 2008. He has a Ph.D. in Civil Engineering from the University of Toronto, awarded in 1980. He has more than thirty-five years of experience with petroleum service and technology companies. He worked for Dowell and Dowell Schlumberger in Denver, Tulsa, and Houston, with TerraTek in Salt Lake City, Advantek International in Houston, and ASRC Energy Services in Anchorage. He has worked on projects concerned with subsurface energy recovery and storage (hydrocarbon, geothermal) in a variety of reservoir environments throughout the world. He is a co-principal investigator on the DOE FORGE project (Frontier Observatory for Research in Geothermal Energy) and an American Rock Mechanics Association (ARMA) Fellow.',
    ],
    expertise: [
      'Subsurface formation characterization from hydraulic, mechanical, and thermal perspectives.',
      'Subsurface engineering including hydraulic stimulation, fluid and slurry injection, and wellbore integrity.',
    ],
    achievements: [
      'Publications: https://scholar.google.com/citations?user=S6xW5H8AAAAJ&hl=en',
      'Member of AIChE, SPE, SPWLA, ARMA, Geothermal Rising',
      'Fellow of American Rock Mechanics Association (ARMA)',
      'Past President of American Rock Mechanics Association (ARMA)',
    ],
    image: '/images/team/john-mclennan.webp',
    imageAlt: 'A Head Shot of John McLennan.',
    leadership: true,
  },
  {
    slug: 'bill-odonnell',
    name: 'Bill O’Donnell',
    role: 'Hydronic Specialist',
    credentials: 'P.E.',
    email: 'bodonnell@greyedgegroup.com',
    phone: '801-244-8800',
    website: null,
    linkedin: 'https://www.linkedin.com/in/bill-o-donnell-64042a22/',
    bio: [
      'William “Bill” O’Donnell PE: Bill O’Donnell has over 42 years of Mechanical Engineering expertise and has developed a diverse combination of skills. Bill brings a history of combining fresh ideas, excellent technical skills, team building capabilities and carefully planned, often innovative solutions to meet short and long term goals.',
      'Mr. O’Donnell and QGE have performed building HVAC & R (Heating, Ventilating, Air Conditioning and Refrigeration) and Plumbing/Piping design and implementation utilizing computer programs for all design aspects including energy loss and analysis. These designs have included geothermal heat pumps, boilers, chillers, forced air gas and roof-top systems. QGE has produced compatible drawings utilizing AutoCAD to fit into the overall project scheme and support the design team. Bill is proficient with engineering and energy analysis programs and has designed hydronic heating and cooling systems utilizing the latest state of the art control systems, piping materials and high efficiency equipment. Systems have included radiant floor heating and cooling, four pipe, four pipe/two pipe hybrids, and two-pipe, and geothermal heat pump systems and ground source loops and wells. Bill has performed troubleshooting of other plumbing and heating and cooling systems to provide maximum system performance.',
      'Most projects have included initiating new designs and improving existing design. QGE has revised instruction manuals and improved training in areas including Engineer and Craftsman initial and continuing training, raising expected standards for technical knowledge and practical abilities. Bill has developed programs for improved pre-engineering of jobs, worker skills and mock-up training.',
    ],
    expertise: [],
    achievements: [],
    image: '/images/team/bill-odonnell.webp',
    imageAlt: "Head Shot of Bill O'Donnell.",
    leadership: true,
  },
  {
    slug: 'roshan-revankar',
    name: 'Roshan Revankar',
    role: 'Professional Engineer',
    credentials: 'PE, CGD, CGI, BESA',
    email: 'rrevankar@greyedgegroup.com',
    phone: '405-564-4991',
    website: null,
    linkedin: 'https://www.linkedin.com/in/roshannrevankar/',
    bio: [
      'Roshan Revankar is on a mission to make ground source energy affordable. He has expertise in geothermal design and energy modeling and is also involved in writing standards and codes for various organizations. Roshan holds a master’s degree in Mechanical Engineering from Oklahoma State University and is a certified building simulation analyst by Association of Energy Engineers and certified geothermal designer and inspector by IGSHPA. He is the current Chair of ASHRAE’s technical committee for geothermal and he serves on various technical committees at IAPMO to develop standards and codes for ground source technology. Roshan is a Professional Engineer.',
    ],
    expertise: [
      'Roshan enjoys the design process for ground source and has worked with several facets in this industry including heat pump manufacturers, drillers and installers. He has trained over 300 professionals in the last 12 years. Roshan is a co-founder and partner at Genesys NZE working to develop low cost ground heat exchangers. He is also a partner at Melink Zero where the team has advanced thermal energy storage products using phase change materials. Roshan has previously served as the Executive Director at IGSHPA where he developed training and membership programs and also established the organization internationally. He has served the role of an industry advocate and has been invited as a speaker nationally and internationally.',
    ],
    achievements: [
      'Designed first Net Zero office facility with Thermal Energy Storage using PCM',
      'Designed and commissioned multiple geothermal schools in Ohio',
      'Patented system design using geothermal with thermal energy storage',
      'Co-founded ground water based heat exchanger to reduce cost of geothermal systems',
      'Selected by DOE’s innovators program in building energy innovations (IMPEL)',
    ],
    image: '/images/team/roshan-revankar.webp',
    imageAlt: 'Roshan Revankar Head Shot',
    leadership: true,
  },
  {
    slug: 'garry-sexton',
    name: 'Garry Sexton',
    role: 'Geothermal Specialist',
    credentials: 'CGD',
    email: 'gsexton@greyedgegroup.com',
    phone: '870-373-0801',
    website: null,
    linkedin: 'https://www.linkedin.com/in/garry-sexton-6a06b478/',
    bio: [
      'Garry is a native of Arkansas, USA and has participated in HVAC mechanical engineering projects for 38 years. He has participated in the development of renewable and sustainable energy projects utilizing innovative technologies and has extensive experience with conceptual engineering design, project management and installation execution for projects throughout the USA, China and South Korea. His projects have ranged from industrial, agricultural and residential to large skyscrapers and include both private industry and governmental institutions. His responsibilities have included management of US and international sales and engineering teams, plus training and certification of geothermal designers and engineers.',
      'During his career he served fifteen years at WaterFurnace in both domestic and international sales engineering, training director at ClimateMaster, and most recently CEO of Innergie Technologies, Inc. Garry has engaged in several engineering projects for the US Military in South Korea and served as the geothermal heat pump SME (Source Matter Expert) for the US Army Corps of Engineers. His qualifications have included certification as the CGD (Certified Geothermal Designer) and Accredited Installation Contractor from IGSHPA (International Ground Source Heat Pump Association) guest lecturer for Tsinghua University, Beijing, China. Other certifications include ACCA (Air Conditioning Contractors of America) Certified Instructor, Type IV Universal Refrigeration Certification, Licensed Mechanical HVAC-R Contractor. He is actively involved in SAME (Society of American Military Engineers) and served as the post chapter vice president for South Korea from 2011-2015.',
    ],
    expertise: [],
    achievements: [
      'Changzhou Pharmaceutical Office & Manufacturing Complex, Changzhou, China — Closed Loop Ground Source Heat Pump System, Capacity 1,150 Refrigeration Tons, 356 Vertical Boreholes, HX Depth 500’',
      'Media Center 2008 Olympics, Qingdao, China (Qingdao Harbor) — Open Loop Seawater Source Heat Pump System, Capacity 550 Refrigeration Tons, Titanium Plate Heat Exchangers (primary/secondary isolation pumping configuration)',
      'China Expo 2010, Shanghai, China (Huang Pu Jiang River) — Open Loop River Water Heat Pump System, 9,860 Refrigeration Tons, Stainless Steel Plate Heat Exchangers (primary/secondary isolation pumping configuration)',
      'Lotte Tower, Seoul, Korea (123 story office/retail/residential)',
      'Guacheon National Science Museum, Seoul, Korea — Closed Loop Ground Source Heat Pump System, Capacity 450 Refrigeration Tons, 130 Vertical Boreholes, HX Depth 660’',
      'Seoul City Hall, Seoul, Korea — Closed Loop Ground Source Heat Pump System, Capacity 1,030 Refrigeration Tons, 280 Vertical Boreholes, HX Depth 670’ (boreholes located under building footprint)',
    ],
    image: '/images/team/garry-sexton.webp',
    imageAlt: 'Garry Sexton Head Shot',
    leadership: true,
  },
  {
    slug: 'mark-smith',
    name: 'Mark Smith',
    role: 'Design Lead',
    credentials: 'CGD, CGI, AI',
    email: 'msmith@greyedgegroup.com',
    phone: '801-942-6100',
    website: null,
    linkedin: 'https://www.linkedin.com/in/mark-smith-a50442179/',
    bio: [
      'Vice President of Sound Geothermal Corporation and Member of TGEG, Mark returned to Sound Geothermal after serving 4 years in the Navy as a Hospital Corpsman. Prior to entering the Navy, he spent two years with Sound Geothermal as a technician which during this time Mark developed his knowledge through hands-on ground loop installations. He has also worked as a driller’s assistant. For the past 16 years he has been in charge of special projects for SGT. Mark has had extensive training in system loads, equipment for all product lines, solar specialties, hydraulics, heat pump operation, and system troubleshooting. Mark is a Certified Geo-Exchange Designer, Certified Geo-Exchange Inspector, an accredited IGSHPA Installer, and owns and operates a ground loop installation and geothermal services company. This combination of specialized training and extensive hands-on experience with both the ground loop and building mechanical systems has provided Mark with the skills to design and troubleshoot systems of all sizes. His primary duties currently include commercial design, field inspection/validation, troubleshooting, and AutoCAD drafting.',
    ],
    expertise: [],
    achievements: [
      'UNG Nephi Readiness Center, 2019–2023: Conventional ground loop heat exchanger to serve the new readiness building being constructed in Nephi, Utah.',
      'USU Moab Academic Building, 2019–2022: Conventional ground loop heat exchanger to serve the net zero academic building for Utah State University.',
      'Weber State University Dee Event Center, 2022–current: Hybrid ground loop heat exchanger to serve the mechanical retrofit for the building.',
      'Weber State University Noorda Building, 2020: Ground loop heat exchanger designed to serve the Noorda building and to supplement the campus conversion of their chilled water loop.',
      'CMU — Extension of the Geo-Exchange System Central Heat Transfer Loop to the northwest of Monument Hall to connect the new and future student dormitories and other campus loads in the future.',
      'CMU — Global Campus Control System RFP. This project developed the control software and necessary hardware to run the Central Heat Transfer Loop and connected campus sources and loads from a central computer dashboard.',
    ],
    image: '/images/team/mark-smith.webp',
    imageAlt: 'Mark Smith Head Shot',
    leadership: true,
  },
  {
    slug: 'megan-lim',
    name: 'Megan Lim',
    role: 'Education and Business Development',
    credentials: null,
    email: 'mlim@greyedgegroup.com',
    phone: null,
    website: null,
    linkedin: 'https://www.linkedin.com/in/lim-megan/',
    bio: [
      'At GreyEdge, Megan is an Education and Business Development Consultant. She works on communicating thermal energy networks — how they work, their tradeoffs, case studies, etc — to various stakeholders. She contributes to business development in the Northeast and youth engagement with the TENs industry.',
      'Megan graduated from MIT in 2024 with a bachelor’s degree from the Sloan School of Management. She is exploring how educational systems, industry, governments, and communities-at-large can work together on community challenges – and engage youth while doing so. She is passionate about workforce development, especially through creating more real-world opportunities for students. Starting her senior year in college, she began contributing to a student-alumni proposal to decarbonize MIT’s campus by 2035 through thermal energy networks (MITTEN). While interviewing the top experts in geothermal, she met GreyEdge members and joined the team in May 2025. Before joining GreyEdge, she worked with MIT Office of Sustainability on student engagement, MIT Environmental Solutions Initiative on climate education (including a K-12 geothermal systems curriculum), and MIT D-Lab on supporting student projects for the first TENs college introductory course modeled after the Certified GeoExchange Designer Course (led by Susan Murcott). Megan currently leads Stakeholder Relations for the Geo@MIT student team, supports TENs and youth engagement resource development for Run on Climate, sits on the Cambridge Climate Committee, and co-leads the MA (Student) Cross Campus Climate Coalition.',
    ],
    expertise: [],
    achievements: [
      '2024 Energy Tech University Prize’s National Geothermal Technologies Bonus Prize Winner (with Geo@MIT)',
      '2025 US Delegate for the UNFCCC-YOUNGO endorsed youth climate change conference (Local Conference of Youth)',
      'Appointed to City of Cambridge’s Climate Committee, beginning February 2025',
      'MIT Alumni for Climate Action and College and University Alumni for a Sustainable Planet',
      'Run on Climate',
      'Co-founder and Stakeholder Relations Lead of Geo@MIT, a student consulting group that equips students with cutting-edge research in thermal energy systems to accelerate the decarbonization of campuses and cities',
      'Cross Campus Climate Coalition, which brings together students of higher education institutions to contribute to campus and city climate goals, mainly based in Massachusetts. We are building a cross-sector, intergenerational community of youth and professionals to tackle the climate crisis',
      'Co-Lead of Assembly for Civic Engagement in MA Higher Education, a state-wide initiative to increase student collaboration with each other and the Commonwealth of Massachusetts',
    ],
    image: '/images/team/megan-lim.webp',
    imageAlt:
      'A Head Shot of Megan Lim who is an Education and Business Development Consultant and works on communicating thermal energy networks for The Grey Edge Group.',
    leadership: false,
  },
  {
    slug: 'jaiden-marriott',
    name: 'Jaiden Marriott',
    role: 'Engineer',
    credentials: null,
    email: 'jmarriott@greyedgegroup.com',
    phone: null,
    website: null,
    linkedin: 'https://www.linkedin.com/in/jaiden-marriott-8b1858379/',
    bio: [
      'A native of Ogden, Utah, Jaiden Marriott is an Energy Engineering graduate of Weber State University and an Engineer in Training at The GreyEdge Group. He focuses on the engineering and design of complex thermal energy systems, energy modeling, and district energy feasibility studies that support the transition to low-carbon, resilient infrastructure.',
      'Jaiden’s senior research at Weber State analyzed the geothermal bore field at the Engineering Building, where he developed a detailed energy model to estimate ground temperature behavior, evaluated system performance, and implemented optimized control strategies to improve system operation. Those experiences helped shape his systems-focused approach to geothermal and electrified thermal networks.',
      'At The GreyEdge Group, Jaiden contributes to large-scale feasibility studies, energy modeling efforts, and thermal system design projects, helping clients assess and optimize pathways to electrification and decarbonization. His work reflects a dedication to practical, infrastructure-first solutions for district energy retrofit and renewable integration.',
      'Outside of technical work, Jaiden is passionate about sustainability, renewable energy, and building lasting relationships — one of his favorite parts of the industry. He enjoys connecting with others who share an interest in advancing clean energy solutions and sustainable communities.',
    ],
    expertise: [],
    achievements: [
      'Association of Energy Engineers (AEE)',
      'American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE)',
      'Engineer in Training: Fundamentals of Engineering (FE) Exam — Passed',
    ],
    image: '/images/team/jaiden-marriott.webp',
    imageAlt: 'A Head Shot of Jaiden Marriott who is in an Engineering role at GreyEdge',
    leadership: false,
  },
  {
    slug: 'ian-talbot',
    name: 'Ian Talbot',
    role: 'Engineer',
    credentials: null,
    email: 'italbot@greyedgegroup.com',
    phone: '385-348-0281',
    website: null,
    linkedin: 'https://www.linkedin.com/in/ian-talbot-a5b340254/',
    bio: [
      'Ian grew up working on his family’s cherry orchard, where he developed a strong work ethic and a practical, hands-on approach to problem solving that continues to influence his engineering work.',
      'Ian earned his degree in Energy Engineering (BS) from Weber State University and is a certified Engineer in Training (EIT), having passed the Fundamentals of Engineering (FE) exam. As part of his senior project, he developed a solar gain calculator used to estimate solar heat gain on buildings, reflecting his interest in applied energy analysis.',
      'His work emphasizes analytical rigor, technical accuracy, and continuous improvement, with a focus on applying engineering principles to real-world challenges. Outside of work, he enjoys hands-on technical hobbies, including 3D printing, vacuum casting, and microprocessor and microcontroller-based projects.',
    ],
    expertise: [],
    achievements: [
      'Association of Energy Engineers (AEE)',
      'American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE)',
      'Engineer in Training: Fundamentals of Engineering (FE) Exam — Passed',
    ],
    image: '/images/team/ian-talbot.webp',
    imageAlt: 'A Head Shot of Ian Talbot who focuses on the engineering and design of complex thermal energy systems for GreyEdge.',
    leadership: false,
  },
  {
    slug: 'delaini-moss-marriott',
    name: 'DeLaini Moss Marriott',
    role: 'Marketing',
    credentials: null,
    email: 'dmarriott@greyedgegroup.com',
    phone: null,
    website: null,
    linkedin: 'https://www.linkedin.com/in/delaini-moss-marriott-1a1094370/',
    bio: [
      'DeLaini is a multidisciplinary creative professional who is passionate about transforming ideas into meaningful visual experiences. Drawn to both the creative and strategic sides of design, she has cultivated a unique blend of expertise in marketing, graphic design, interior design, and business, allowing her to approach every project with curiosity, purpose, and a user-centered mindset. She believes great design is more than aesthetics—it is about solving problems, communicating ideas, and creating meaningful connections.',
      'At The Grey Edge Group, DeLaini has gained experience working alongside engineers and technical professionals, learning how to translate complex concepts into clear, engaging visual communications. Whether developing proposals, creating branded materials, or supporting business development initiatives, she enjoys finding creative solutions that make technical information more accessible and impactful. Currently pursuing a bachelor’s degree in Business Management with emphases in Interior Design and Digital Marketing, she is committed to continually expanding her skills while creating work that is both thoughtful and effective.',
    ],
    expertise: [
      'DeLaini’s expertise spans creative direction, brand development, graphic design, visual storytelling, and digital marketing. Proficient in AutoCAD, SketchUp, and the Adobe Creative Suite, she seamlessly integrates technical design with compelling visual communication. Her experience in content creation, presentation design, photography, videography, and project coordination enables her to deliver creative solutions that strengthen brands and effectively engage audiences.',
    ],
    achievements: [
      'Digital Content Creation Certificate',
      'Interior Design Certificate',
      'Social Media Marketing Certificate',
      'Hospitality & Tourism Management Certificate',
      'Proficient in Adobe InDesign, Premiere Pro, Illustrator, and Photoshop',
      'Proficient in AutoCAD',
      'Proficient in SketchUp',
      'BAS of Business Management (current)',
      'AAS of Interior Design (current)',
    ],
    image: '/images/team/delaini-moss-marriott.webp',
    imageAlt: 'A Head Shot of DeLaini Moss Marriott who has a marketing-focused role at The Grey Edge Group.',
    leadership: false,
  },
]

const orderIndex = (slug: string) => {
  const i = (teamOrder as readonly string[]).indexOf(slug)
  return i === -1 ? Number.MAX_SAFE_INTEGER : i
}
team.sort((a, b) => orderIndex(a.slug) - orderIndex(b.slug))

export const leadership = team.filter((m) => m.leadership)

export const getMember = (slug: string) => team.find((m) => m.slug === slug)
