// GENERATED by scripts/import-wp.mjs — edit the script or re-run `pnpm import:wp`
// rather than hand-editing, or your changes will be overwritten on the next import.

export interface BioSection {
  heading: string
  items: string[]
}

export interface TeamMember {
  slug: string
  name: string
  role: string
  credentials: string | null
  email: string | null
  phone: string | null
  website: string | null
  linkedin: string | null
  bio: string[]
  /** Awards, publications, education etc. — varies per person. */
  sections: BioSection[]
  image: string | null
  imageAlt: string
  leadership: boolean
}

/** Grid order from the legacy Our Team page (5-across). */
export const teamOrder = [
  'matthew-garlick',
  'richard-b-white',
  'cary-smith',
  'paul-bony',
  'garen-ewbank',
  'stephen-hamstra',
  'john-mclennan',
  'bill-odonnell',
  'roshan-revankar',
  'garry-sexton',
  'mark-smith',
  'jaiden-marriott',
  'megan-lim',
  'delaini-moss-marriott',
  'ian-talbot',
] as const

export const team: TeamMember[] = [
  {
    slug: "matthew-garlick",
    name: "Matthew Garlick",
    role: "CEO",
    credentials: "CCP, CxA, CEM, BEMP",
    email: "mgarlick@greyedgegroup.com",
    phone: null,
    website: null,
    linkedin: null,
    bio: [
      "Matt Garlick is a man who loves what he does! Leading The GreyEdge Group as CEO gives him a chance to use his superpower- communicating technical information to people who don’t currently speak “geothermal”. Bridging the gap between GreyEdge’s incredible experience in Thermal Energy Networks and town, campus, and utility customers, Matt pushes forward the concept of TENs as the most efficient and lowest carbon alternative to standard heating and cooling systems.",
      "Matt holds a Master of Architecture degree from the University of Utah and is a Building Energy Modeling Professional (BEMP, ASHRAE), a Certified Energy Manager (CEM, AEE) and a Certified Commissioning Professional (CCP, BCxA). Matt is an advocate for high performance design and regularly speaks to professional organizations across the nation on the benefits and potential for TENs. In an industry filled with engineers, Matt’s combination of a broad understanding and technical expertise allows him to reduce complicated ideas into simpler forms. This helps bridge the worlds of owners, architects, engineers and contractors and encourages efficient systems that deliver in the real world.",
      "Matt’s career has led to working on building typologies that have the most to gain from energy efficiency. He has developed energy models and provided design teams with actionable recommendations on over 12,000,000sf of projects from China to Canada and California to New York. He has led teams on dozens of commissioning and retrocommissioning projects over the past ten years. This broad mastery of conceptual and practical concepts elevates his work at the GreyEdge Group developing real world applications for Ambient Temperature Loops."
    ],
    sections: [
      {
        heading: "Awards",
        items: [
          "2023 Building Commissioning Association 20 Under 40"
        ]
      },
      {
        heading: "Publications",
        items: [
          "Energy is a Design Problem, AIA Utah Reflexion",
          "Saving Green While Being Green, Utah Construction and Design"
        ]
      }
    ],
    image: "/images/team/matthew-garlick.webp",
    imageAlt: "A Head Shot of Matthew Garlick who the CEO of The Grey Edge Group.",
    leadership: true
  },
  {
    slug: "richard-b-white",
    name: "Richard B. White",
    role: "Chairman of the Board",
    credentials: null,
    email: "rwhite@greyedgegroup.com",
    phone: "801-673-6647",
    website: "http://www.rbwhitepe.com/",
    linkedin: null,
    bio: [
      "With over 45 years of consulting engineering practice, Rich has substantial experience in the assessment, design, and management of civil and environmental engineering projects. Through this experience, he has gained an in-depth understanding of the critical role that surface and subsurface water, soil, and rock play on project success. He has provided consulting engineering services to small and large mining, oil and gas, chemical, and other industrial concerns as well as local, State, and Federal governments throughout the United States and internationally. His designs have been implemented to restore natural conditions, mitigate past environmental impacts, prevent future impacts, allow aquifer storage and recovery of groundwater, and permit ground-source heat exchange."
    ],
    sections: [
      {
        heading: "Core Competencies",
        items: [
          "Performance of hydrogeologic assessments to evaluate potential groundwater supplies and drilling difficulties",
          "Assessment and mitigation of environmental impacts resulting from land development",
          "Design of disturbed-land reclamation plans",
          "Design of runoff- and sediment-control plans",
          "Design of stream channel stabilization plans",
          "Rapid engineering response to oil spills and other environmental emergencies",
          "Preparation of plans to remediate soil and groundwater contamination",
          "Interaction with regulatory agencies"
        ]
      },
      {
        heading: "Awards",
        items: [
          "Projects designed by Rich have received several local, national, or international awards. These have included:",
          "Excellence in Surface Coal Mining and Reclamation National Award, presented in 2003 by the U.S. Department of Interior, Office of Surface Mining to Castle Gate Holding Company. Rich provided reclamation design and construction quality control services on this project, which was completed at underground coal mining operations in east-central Utah. The award was presented “for outstanding performance in developing and implementing exemplary mining and reclamation methods that maintained sound environmental conditions.”",
          "Best Practice designation, presented in 2002 by the Eurasian-American Partnership for Environmentally Sustainable Economies, for work completed by Rich on a project to minimize environmental impacts and maximize coal recovery from waste rock at an underground coal mine in the Russian Far East. The work was so designated because it demonstrated “environmentally sound and economically efficient solutions to environmental problems in Central and Eastern Europe and Asia.”"
        ]
      }
    ],
    image: "/images/team/richard-b-white.webp",
    imageAlt: "A head shot of Richard B. White Head who is the Chairman of the Board of The Grey Edge Group",
    leadership: true
  },
  {
    slug: "cary-smith",
    name: "Cary Smith",
    role: "CFO",
    credentials: "CEM, CEA, CGD, CGI, AEE Fellow",
    email: "csmith@greyedgegroup.com",
    phone: "801-244-8800",
    website: "https://www.soundgt.com/",
    linkedin: null,
    bio: [
      "Mr. Smith President/CEO of Sound Geothermal Corporation (SGT). Mr. Smith is also CFO and a Director of The GreyEdge Group, an international consulting firm specializing in district energy applications.",
      "The GreyEdge Group (TGEG) specializes in engineering, master-planning, and design of complex thermal energy network systems using the Thermal Highway©. These are also known as an Ambient Temperature Loop (ATL) or Thermal Energy Network (TEN). Successful systems are operating around the world delivering clean and comfortable heating and cooling on projects ranging from single-family homes to large district geothermal systems including university campuses and a 123-story skyscraper.",
      "SGT is an innovative design group focusing on various energy saving building technologies utilizing ground source heat pump (GeoExchange)® systems or other renewable energy systems as a core technology. SGT has contributed to the development or innovation of mid-temperature and low temperature geothermal applications.",
      "These systems include, cascading mid to low temperature geothermal systems, hybrid systems which combine GeoExchange with other technologies such as solar thermal or conventional HVAC (Heating Ventilating Air Conditioning) components. They have also had significant success with district energy systems which share energy between buildings, limit demand, and may incorporate additional components such as co-generation or solar photovoltaic.",
      "Mr. Smith is a co-developer of the Ambient Temperature System (ATL). He has designed over twenty systems since 2002 including Colorado Mesa University and Weber State University. He currently holds consulting positions on multiple city scape, commercial, military, and industrial projects.",
      "Prior to starting SGT and, Mr. Smith was the founding Principal and President of Applied Drilling Services Inc., a consulting petroleum engineering and business development firm with 25 years in the oil and gas energy management industry. Cary has over 50 of years’ experience in the fields of energy consulting, exploration and development, and energy systems design. His strong financial background has served a wide variety of renewable energy industry, petroleum industry, municipal, and industrial clients in successful energy related projects. Substantial experience in",
      "energy technology, GeoExchange system design, and financial management provides a great asset to the clients of Sound Geothermal. Cary is responsible for the majority of the large commercial and school designs in SGT’s portfolio.",
      "He served(s) on the International Association of Plumbing and Mechanical Officials (IAPMO) 2020 through 2030 UMC Technical committees and 2018 through 2026, USHGC Code Committees. He was Chair of the 2024 USHGC Code Committee and Chair of the Ambient Temperature Loop Standard Committee . IAPMO/ANSI/CAN Z1381-2025",
      "Mr. Smith’s professional affiliations also include the Geothermal Heat Pump Consortium (GEO), International Ground Source Heat Pump Association (IGSHPA), Association of Energy Engineers (AEE), American Society of Heating Refrigeration and Air-conditioning Engineers (ASHRAE), and the National Ground Water Association (NGWA). He has held a number of leadership roles in most of these organizations and is the past Chairman of ASHRAE’s national Technical Committee 6.8, Geothermal Utilization and Heat Recovery. In addition, he is Past-Chair of ASHRAE MTG _ Avoided Source Energy Consumption (ASEC). He also served on the IGSHPA Board of Directors, Training, Advocacy, and Standards committees.",
      "Mr Smith also serves on the Utah Energy Office Beneficial Electrification Committee and the Colorado State Geothermal Committee.",
      "He holds multiple professional certifications including; Certified GeoExchange Designer, Certified Energy Manager, Certified GeoExchange Inspector, and Certified Energy Auditor (CGD, CEM, CEA). He is a co-author of, and teaches, the Certified Geothermal Inspector and Certified Geothermal Designer courses."
    ],
    sections: [],
    image: "/images/team/cary-smith.webp",
    imageAlt: "A Head Shot of Cary Smith who is the CFO of The Grey Edge Group",
    leadership: true
  },
  {
    slug: "bill-odonnell",
    name: "Bill O’Donnell",
    role: "Engineering",
    credentials: null,
    email: "bodonnell@greyedgegroup.com",
    phone: "801-244-8800",
    website: null,
    linkedin: null,
    bio: [
      "William “Bill” O’Donnell PE: Bill O’Donnell has over 42 years of Mechanical Engineering expertise and has developed a diverse combination of skills. Bill brings a history of combining fresh ideas, excellent technical skills, team building capabilities and carefully planned, often innovative solutions to meet short and long term goals.",
      "Mr. O’Donnell and QGE have performed building HVAC & R (Heating, Ventilating, Air Conditioning and Refrigeration) and Plumbing/Piping design and implementation utilizing computer programs for all design aspects including energy loss and analysis. These designs have included geothermal heat pumps, boilers, chillers, forced air gas and roof-top systems. QGE has produced compatible drawings utilizing AutoCAD to fit into the overall project scheme and support the design team. Bill is proficient with engineering and energy analysis programs and has designed hydronic heating and cooling systems utilizing the latest state of the art control systems, piping materials and high efficiency equipment. Systems have included radiant floor heating and cooling, four pipe, four pipe/two pipe hybrids, and two-pipe, and geothermal heat pump systems and ground source loops and wells. Bill has performed troubleshooting of other plumbing and heating and cooling systems to provide maximum system performance.",
      "Most projects have included initiating new designs and improving existing design. QGE has revised instruction manuals and improved training in areas including Engineer and Craftsman initial and continuing training, raising expected standards for technical knowledge and practical abilities. Bill has developed programs for improved pre‑engineering of jobs, worker skills and mock‑up training.",
      "Beginning in 1973, Bill held increasingly responsible mechanical engineering positions in project engineering, plant operations, maintenance, training, and high quality manufacturing processes for the Westinghouse Electric Corporation, 1973 to 1991. 1991 to present, numerous challenges as Manager of the Quantum Group Engineering, PC. Assignments have included: Commercial building design involving HVAC & R, geothermal heat pumps, plumbing and piping design, energy analysis and savings, Indoor Air Quality and related engineering work; Aeroflow Oil‑Free Air and Gas Compressors in all aspects of air and gas compressor design, manufacturing, vendor development, assembly, testing and customer feedback.",
      "Bill received his BS in Mechanical Engineering from California Polytechnic State University. Mr. O’Donnell is licensed as a Professional Engineer in Colorado (#37526), Utah (#813816), Wyoming (#8956) and Idaho (#4136). He is also a member of the American Society of Heating, Refrigeration and Air-Conditioning Engineers (ASHRAE)"
    ],
    sections: [
      {
        heading: "Quantum Group Engineering",
        items: [
          "543 West 19th ST Idaho Falls, ID 83402 208-523-8068 Principal: Bill O’Donnell PE",
          "Quantum Group Engineering PC is an Idaho Falls based professional engineering firm that works throughout the intermountain west including Utah, Wyoming and Colorado. Specialties include all aspects of Mechanical Engineering Services including new construction, remodels and upgrades, and implementing energy reducing technologies. We also provide mechanical and control system problem solving and energy consumption analyses. Our firm has been in business for 20 years; however, the owners and others have performed engineering work in the Intermountain West including Utah for this and other firms for over 40 years. This a professional corporation with William E. O’Donnell and H. Quincy O’Donnell as the shareholders, both experienced Professional Mechanical Engineers. William E. O’Donnell is a licensed in the State of Idaho (#4136) for over 33 years and is also licensed in Colorado (#37526), Utah (#813816), and Wyoming (#8956). Mr. H. Quincy O’Donnell, a graduate mechanical engineer from the University of Idaho and a licensed Mechanical Engineer in Idaho. We work mostly in Eastern Idaho, Western Wyoming, Utah and Colorado.",
          "All of our larger building projects and most of our smaller building projects have DDC (Direct Digital Control) and/or micro-processor based control systems that assist in data logging, trend analysis, mechanical system commissioning, proper building system functionality and energy efficiency. Building and System Load Analyses are performed using TRACE ®700 to develop envelope and project systems with low life cycle costs.",
          "Our firm has teamed with Sound Geothermal (Sandy, Utah), to perform a number of campus type projects including the Geo-Exchange Central Loop and Global Control System RFP at Colorado Mesa University in Grand Junction, Colorado. Sound Geothermal is an expert in geo-exchange and we provide the licensed professional mechanical engineering services to complete the team. We have found this to be a very complimentary and successful relationship. We have worked with Sound Geothermal since 1999 on many projects in Utah, Idaho, and Wyoming as well as other states."
        ]
      }
    ],
    image: "/images/team/bill-odonnell.webp",
    imageAlt: "Head Shot of Bill O'Donnell.",
    leadership: true
  },
  {
    slug: "garen-ewbank",
    name: "Garen Ewbank",
    role: "Ground Loop and Drilling Specialist",
    credentials: "B.S. I.E.&M, OSU, AEE Fellow",
    email: "gewbank@greyedgegroup.com",
    phone: "405-826-8156",
    website: null,
    linkedin: null,
    bio: [
      "Garen grew up in the water well and oil and gas drilling industries. Garen’s motto is “keep turning to the right”. Garen has worked in the GSHP industry since 1979 and has been involved in the design and implementation of well over 100,000 MW (millions of feet) of installed heat pump equivalent capacity in North America. Garen was a contributor to several training courses to include the Certified GeoExchange Designer Course and Syllabus that has been adopted by the International Ground Source Heat Pump Association (IGSHPA) and the Association of Energy Engineers. Garen is a member of the Technical Committee to develop the Bi-National CSA/ANSI C448 Standard for the Design and Installation of Ground Source Heat Pumps for Commercial and Residential Buildings. Garen is a founding member of the GreyEdge Group."
    ],
    sections: [
      {
        heading: "Areas of Expertise",
        items: [
          "Garen developed the in situ thermal conductivity testing methodology used by the GSHP industry to size and design ground heat exchangers (GHEX). Garen is co-owner of the patented Advanced Thermal Conductivity Method (ACTM) that shortens the testing duration and quantifies the diffusivity. Garen has installed GHEXs throughout the U.S. and consulted throughout the world on GHEXs. Garen has been a primary investigator/ collaborator on numerous applied research projects on the GHEX, borehole resistance and thermal storage, Garen has peer reviewed several software applications to size and design the GHEX. Garen trains for IGSHPA in all courses domestically and internationally.",
          "Garen is managing member of Ewbank Geo Testing, LLC, member of GeoAire International and at large managing member for The GreyEdge Group, LLC."
        ]
      },
      {
        heading: "Notable Projects & Achievements",
        items: [
          "Pioneered in situ thermal conductivity testing for the ground source heat pump industry in 1994 and the ACTM in 2016.",
          "Developed re-circulating stiff foam drilling methods for lost circulation zones",
          "Researched ground, grout and piping heat transfer",
          "Consulted with state regulators and state drilling associations on GHEX regulations in many states",
          "Co-authored papers for ASHRAE on earth thermal properties, boreholes resistance and piping configurations",
          "Holds patent pending on heat pumps and domestic and international design software; awarded several patents on drilling rigs and water pumping systems",
          "Awarded the grade of Fellow and received the Legends in Energy award with the Association of Energy Engineers",
          "Garen has trained thousands individuals for IGHSPA in all courses",
          "Garen is a member of the Strategic Advisory Council for the College of Engineering, Architecture, and Technology (CEAT) at Oklahoma State University",
          "Garen has served on numerous civic, communities, and financial boards as member and chair"
        ]
      },
      {
        heading: "Professional Affiliations and Publications",
        items: [
          "Member – International Ground Source Heat Pump Association (IGSHPA); Past-President of the Board of Directors; have made numerous presentations at IGSHPA Conferences",
          "Life Member – Association of Energy Engineers (AEE); Member – Oklahoma Chapter of the Association of Energy Engineers, served as President of the Board of Directors and continues as a Board of Directors member (AEEOK); have made numerous presentations nationally, at states and chapters at AEE Conferences",
          "Established the “Roger Farrar” Annual Energy Conference for the Oklahoma Chapter of the Association of Energy Engineers",
          "Member – American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE): Garen has made numerous presentations at ASHRAE Chapter Meetings",
          "Oklahoma Water Resources Board – Licensed to drill in Oklahoma, trainer and presenter for continuing education credits"
        ]
      }
    ],
    image: "/images/team/garen-ewbank.webp",
    imageAlt: "A Head Shot of Garen Ewbank.",
    leadership: true
  },
  {
    slug: "stephen-hamstra",
    name: "Stephen Hamstra",
    role: "Thermal Energy Systems Specialist",
    credentials: "PE, AEE Fellow, ASHRAE HBDP, CGD, LEED AP",
    email: "shamstra@greyedgegroup.com",
    phone: "616-566-6185",
    website: null,
    linkedin: null,
    bio: [
      "Steve grew up in a family HVAC business, his father was an early-adopter of ground-source heat pump (GSHP) systems in the 1970’s. Steve has always had a passion for sustainability and renewable energy, building concentrating solar collectors while in high school and studying various high-performance building design approaches. He served for nearly 4 decades as a principal in an architecture & engineering firm, piloting the design of many energy efficient and innovative projects that included ground-source heat pumps, energy recovery, thermal energy storage, solar PV, etc.",
      "Steve is the Vice-Chair (soon to be Chair) of ASHRAE TC 6.8 Ground-Source Heat Pumps and Energy Recovery, and has designed many, many ground-source systems in his career. He developed and patented a web based GSHP design software, which would automatically export a self-learning control algorithm for large GSHP systems. This control approach has been installed on several military bases, universities and other applications.",
      "Steve is Senior Vice President of Melink Solar & Geo where he is actively engaged in a DOE-funded research project to develop new technology to reduce the marketplace barriers to GSHP, as well as developing and refining Melink’s unique approach to packaged GSHP control and pumping solutions.",
      "Steve is a recent addition as Member of The GreyEdge Group with the goal of expanding the application of high-performance, sustainable approaches to applying heat pump systems, thermal energy storage and renewable energy approaches.",
      "Steve is a Professional Engineer, licensed in Michigan and Ohio. He resides in West Michigan."
    ],
    sections: [
      {
        heading: "Areas of Expertise",
        items: [
          "Steve has several patented innovations in the HVAC marketplace and has enjoyed the design process as well as directing and managing many design professionals for several AE firms.",
          "In addition to his work at Melink Solar & Geo, and his efforts with The GreyEdge Group, he also has his own consulting practice; Zeven Element Design Institute (ZEDI PLC)."
        ]
      },
      {
        heading: "Notable Projects & Achievements",
        items: [
          "ASHRAE 2014 1st Place Global Award for the Low Energy Science Building designed for the University of Findlay. It includes a GSHP, DOAS and radiant heating/cooling.",
          "Several articles published in Engineered Systems Magazine: “V” is for Ventilation “Large Scale Geothermal Heat Pump Systems” “Pumping and Flow Controls in Geothermal Heat Pump Systems”",
          "“V” is for Ventilation",
          "“Large Scale Geothermal Heat Pump Systems”",
          "“Pumping and Flow Controls in Geothermal Heat Pump Systems”",
          "Advisor to ASHRAE and Dr. Steve Kavanaugh on the design handbook; “Ground-Source Heat Pumps: Design of Geothermal Systems for Commercial and Institutional Buildings” published in 2013",
          "Speaker at dozens of ASHRAE, IGSHPA and various green building conferences since the 1990’s.",
          "Steve has served on numerous civic, communities, and advisory boards as member and chair including City Council, Board of Education, Hospital Board, Municipal Utility Board and others."
        ]
      },
      {
        heading: "Professional Affiliations and Publications",
        items: [
          "Member – International Ground Source Heat Pump Association (IGSHPA); have made numerous presentations at IGSHPA Conferences",
          "Member – Association of Energy Engineers (AEE); Past Regional Energy Engineer of the Year winner and Fellow",
          "Member – American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE): Steve has made numerous presentations at ASHRAE Chapter Meetings"
        ]
      }
    ],
    image: "/images/team/stephen-hamstra.webp",
    imageAlt: "A Head Shot of Steve Hamstra.",
    leadership: true
  },
  {
    slug: "paul-bony",
    name: "Paul Bony",
    role: "Energy Services Professional",
    credentials: null,
    email: "pbony@greyedgegroup.com",
    phone: "970-209-0999",
    website: null,
    linkedin: null,
    bio: [
      "Accomplished professional with deep experience in the conditioned space, energy efficiency, utility, and clean energy industries. Results oriented nationally recognized expert with proven success establishing and developing high value relationships, programs, services and profit streams benefiting all stakeholders. A passionate leader in the product delivery, financing, utility and contractor development arenas. President of the Solar Energy International Board of Directors and a member of the International Ground Source Heat Pump Association Board of Directors."
    ],
    sections: [
      {
        heading: "Core Competencies",
        items: [
          "Business Development ~ Client Relations ~ Technical Sales ~ Marketing ~ Public Speaking ~Training ~ Policy Project Management ~ Process Improvement ~ Consumer Finance ~ Operations Efficiency ~ Lobbying Market Analysis ~ Market Assessment ~ Contract Negotiation and Management ~ Economic Modeling ~ Networking Program Development ~ Strategic Planning ~ Proficiency in Microsoft Office Products"
        ]
      },
      {
        heading: "Key Accomplishments",
        items: [
          "Developed new markets and strategic opportunities, including: established ClimateMaster as the preferred partner in a major utility program and in a net zero military project built the Nation’s first off-grid PV leasing program created the first utility-owned renewable ground-source heat pump loop tariff brought Carrier Corp to EGIA, resulting in revenues benefiting both firms in the U.S. and Canada created and launched the national Home Energy Makeover Contest hosted the first U.S. propane powered fuel cell outside of a laboratory, leading to the successful Plug Power IPO",
          "established ClimateMaster as the preferred partner in a major utility program and in a net zero military project",
          "built the Nation’s first off-grid PV leasing program",
          "created the first utility-owned renewable ground-source heat pump loop tariff",
          "brought Carrier Corp to EGIA, resulting in revenues benefiting both firms in the U.S. and Canada",
          "created and launched the national Home Energy Makeover Contest",
          "hosted the first U.S. propane powered fuel cell outside of a laboratory, leading to the successful Plug Power IPO",
          "Founded and served as the Operations Manager of a HVAC company. Developed and implemented business plans and staffing, financial forecasts, marketing plans, pricing models, operating procedures and drove sales. Reached rapid profitability and exceeded revenue goals",
          "Managed business operations with annual billings in excess of $25 Million, over 40 employees and had responsibility for annual operating budgets up to $5 Million",
          "Board President Solar Energy International, International Ground Source Heat Pump Association Board Member, Board Member Montrose Economic Development Corporation, Past Chair of the California Utility Energy Forum; appointed to the Cooperative Research Network Energy Efficiency and Demand Response Advisory Group and the EPRI Demand-Side Management Task Force"
        ]
      },
      {
        heading: "Experience",
        items: [
          "Effectively communicated and presented EGIA’s value proposition to stakeholders by preparing content and presenting to individual dealers in the field, at distributor events, on-line through web-based presentations, and at strategic stakeholder events with revenue growth potential.",
          "Leveraged network contacts and secured new distribution and manufacturer and accounts.",
          "Sold an array of multi-faceted financial platforms to contractors covering the spectrum of residential and commercial financing and leasing options, using a consultative selling approach.",
          "Obtained new clients by managing the sales cycle from finance program application through initial loan funding.",
          "Managed and grew Canadian finance partner’s business and contractor relationships.",
          "Developed and grew relationships with distributors, dealers, customers, utilities, state and regional government organizations and other strategic partners and built the sales pipeline in the U.S. and Canada.",
          "Implemented market development, lead generation and tracking, and sales activities for the product channel, including sales training, product workshops and educational events targeting A&E, policy and environmental groups.",
          "Became a channel expert in product features, benefits, performance, and design guidelines.",
          "Designed training programs and managed the technical training team through intensive new product launches.",
          "Established a leadership role in national building and design trade groups and with green building stakeholders, including serving on panels, presenting white papers, and developing policy at the state and national levels.",
          "Created the original model for the “Home Energy Makeover” contests held in nine markets throughout the U.S. by the Electric & Gas Industries Association.",
          "Implemented efficiency and renewable energy programs that were featured in Time, Business Week, The Denver Post, Energy Services Bulletin, RE Magazine, Solar Today and other regional and national publications.",
          "Provided leadership to the industry in regards to policy, gave expert testimony at the regional, state and national level, collaborated with diverse stakeholder groups, and presented at state and national forums.",
          "Improved financial operations by cutting costs and increasing revenues across all areas of responsibility.",
          "Managed the Co-Op’s satellite subsidiary and the launch of a highly successful and profitable DIRECTV franchise.",
          "Managed all stakeholders leading to California’s first all-geothermal heat pump community.",
          "Developed California’s first utility off-grid photovoltaic electric service.",
          "Developed a nationally-recognized geothermal loop leasing program by leveraging a Department of Energy grant."
        ]
      },
      {
        heading: "Awards",
        items: [
          "Received EPA/DOE “Excellence in Energy Star Outreach” Award",
          "Awarded the Association of Energy Services Professionals “Achievement in Energy Services”",
          "Awarded the National Rural Electric Cooperative Association’s “Best Total Communications Program”"
        ]
      }
    ],
    image: "/images/team/paul-bony.webp",
    imageAlt: "A Head Shot of Paul Bony",
    leadership: true
  },
  {
    slug: "delaini-moss-marriott",
    name: "DeLaini Moss Marriott",
    role: "Marketing and Creative",
    credentials: null,
    email: "dmarriott@greyedgegroup.com",
    phone: null,
    website: null,
    linkedin: null,
    bio: [
      "DeLaini Moss Marriott has a marketing-focused role at The Grey Edge Group, where she develops visually compelling proposals, graphics, presentations, and media assets. She is currently pursuing a bachelor’s degree in Business Management with an emphasis in Interior Design and Digital Marketing at Ensign College in Salt Lake City, Utah."
    ],
    sections: [
      {
        heading: "Education",
        items: [
          "BS in Business Management – Ensign College (current)",
          "AS in Interior Design – Ensign College (current)"
        ]
      },
      {
        heading: "Certificates",
        items: [
          "Digital Marketing – Ensign College (current)",
          "Digital Content Creation – Ensign College (current)",
          "Hospitality and Tourism Management – Ensign College 2023"
        ]
      }
    ],
    image: "/images/team/delaini-moss-marriott.webp",
    imageAlt: "A Head Shot of DeLaini Moss Marriott who has a marketing-focused role at The Grey Edge Group.",
    leadership: false
  },
  {
    slug: "garry-sexton",
    name: "Garry Sexton",
    role: "Renewable Energy Engineering and Design",
    credentials: null,
    email: "gsexton@greyedgegroup.com",
    phone: "870-373-0801",
    website: null,
    linkedin: null,
    bio: [
      "Thirty eight years of direct involvement in multiple aspects of engineering, design and consulting within renewable and alternative energy industries. Active work experience includes application engineering, sales and technical training, renewable energy designer, application/sales engineer, senior project management, product development, project creative concept design & development and founder/CEO of Innergie Technologies, Inc."
    ],
    sections: [
      {
        heading: "Career History",
        items: [
          "Established international renewable energy engineering consulting/design and HVAC heat pump distribution companies.",
          "Developed Sales and Engineering Services Divisions within Korea with double digit annual growth.",
          "Developed HVAC Sales Division for US Army projects in Korea",
          "Built Engineering Design & Consulting Services for China and Korea",
          "Providing onsite engineering HVAC support, project supervision, technical support, product engineering training for technical engineering staff",
          "International engineering sales and marketing program for Asia-Pacific region",
          "Developed and taught training courses IGSHPA certified training",
          "Increased market sales by over 100%",
          "Exceeded sales targets by 50%",
          "Established and trained new distribution representatives throughout Asia-Pacific region",
          "Managed a staff of 19 employees and three project managers",
          "Directed the oversight and management of multiple subcontractors",
          "Provided interface for US Military/DOD projects at locations throughout the United States",
          "Provided technical and engineering oversight for large installations and mechanical HVAC systems totaling over $65 million in contracts",
          "Completed projects on time and under budget, resulting in consistently satisfied customers",
          "Established certified training program at ClimateMaster",
          "Provided application engineering for distribution & dealer network",
          "Developed sales and technical training seminars for USA/Canada",
          "Developed successful HVAC contractor training program for geothermal HVAC systems",
          "Established and implemented training courses for Territory Sales Managers",
          "Developed train the trainer geothermal technical sales programs",
          "Recruited and trained staff technical training employees",
          "Served WFI in positions as Territory Senior Territory Sales Manager and Application Engineering Manager",
          "Coordinated and managed commercial engineering and HVAC Installation projects",
          "Supervised installation crew scheduling, job coordination and employees to meet project completion deadlines",
          "Direct oversight of budgets and services for customer fulfillment and project specifications",
          "Managed in-house and field staff for HVAC operations including technical and contracting services",
          "Coordinated estimation and bidding processes to secure contracts for two large hospital projects in Kansas City, MO and Harrison, AR",
          "Scheduled and motivated employees to secure on time contract fulfillment"
        ]
      },
      {
        heading: "Past & Present Associations & Education",
        items: [
          "US Army – EE Diploma (Technical Electronics Engineer)",
          "HVAC Apprenticeship Program, Dallas, TX",
          "Evangel University, (BA Business Management & Minor Psychology) Springfield, MO",
          "IGSHPA (International Ground Source Heat Pump Association) Oklahoma State University, Train the Trainer Certified , Certified Installation Contractor",
          "IGSHPA Certified Instructor- geothermal certification courses OSU – Stillwater, instructor for training in USA, Canada, England, Australia, China, Korea",
          "CGD – Geothermal Heat Pump Design & Engineering (CGD – Certified Designer) IGSHPA-Oklahoma State University",
          "ACCA (Air Conditioning Contractors of America)",
          "EPA –USA Environmental Protection Agency – Type IV, Universal Refrigeration Certification (application, handling, recovery, disposal)",
          "Licensed Mechanical HVAC-R Contractor",
          "SAME – Society American Military Engineers, Vice President, Korea Post 2011-2015",
          "ASHRAE – Member American Society of Heating/Refrigeration & Air Conditioning Engineers",
          "SME – Certified Source Matter Expert – Geothermal Heat Pump Systems Applications for US Army Corps of Engineers – DOD Resources",
          "AEE – Association of Energy Engineers"
        ]
      },
      {
        heading: "Biography",
        items: [
          "Garry is a native of Arkansas, USA and has participated in HVAC mechanical engineering projects for 38 years. He is the past CEO of Innergie Technologies, Inc. and has participated in the development of renewable and sustainable energy projects utilizing innovative technologies and has extensive experience with conceptual engineering design, project management and installation execution for projects throughout the USA, China and South Korea. His projects have ranged from industrial, agricultural and residential to large skyscrapers and include both private industry and governmental institutions. His responsibilities have included management of US and international sales and engineering teams, plus training and certification of geothermal designers and engineers.",
          "During his career he served fifteen years at WaterFurnace in both domestic and international sales engineering, training director at ClimateMaster, and most recently CEO of Innergie Technologies, Inc. Innergie Technologies, Inc. was founded by Garry in 2007 with the goal of pursuing design and installation projects worldwide. His company engaged in several engineering projects for the US Military in South Korea and served as the geothermal heat pump SME (Source Matter Expert) for the US Army Corps of Engineers. His qualifications have included certification as the CGD (Certified Geothermal Designer) and Accredited Installation Contractor from IGSHPA (International Ground Source Heat Pump Association) guest lecturer for Tsinghua University, Beijing, China. Other certifications include ACCA (Air Conditioning Contractors of America) Certified Instructor, Type IV Universal Refrigeration Certification, Licensed Mechanical HVAC-R Contractor. He is actively involved in SAME (Society of American Military Engineers) and served as the post chapter vice president for South Korea from 2011-2015. (Garry sold his company, Innergie Technologies, Inc. in 2015)",
          "Engineering Design and Consulting Engineering Projects List",
          "Changzhou Pharmaceutical Office & Manufacturing Complex, Changzhou, China Closed Loop Ground Source Heat Pump System, Capacity 1,150 Refrigeration Tons, 356 Vertical Boreholes, HX Depth 500’",
          "Media Center 2008 Olympics, Qingdao, China (Qingdao Harbor) Open Loop Seawater Source Heat Pump System, Capacity 550 Refrigeration Tons, Titanium Plate Heat Exchangers (primary/secondary isolation pumping configuration)",
          "China Expo 2010, Shanghai, China (Huang Pu Jiang River) Open Loop River Water Heat Pump System, 9,860 Refrigeration Tons, Stainless Steel Plate Heat Exchangers (primary/secondary isolation pumping configuration)",
          "Lotte Tower, Seoul, Korea (123 story office/retail/residential)",
          "Closed Loop Ground Source Heat Pump System, 3,300 Refrigeration Tons, 1260 Vertical Boreholes, HX Depth 670’ (boreholes located under footprint of building)",
          "Municipal Water Source Heat Pump System, 3,300 Refrigeration Tons, Stainless Steel Plate Heat Exchangers (primary/secondary isolation pumping configuration)",
          "Waste Water Source Heat Pump System, 1,200 Refrigeration Tons, Stainless Steel Plate Heat Exchangers) primary/secondary pumping configuration",
          "Total Building HVAC load 30,400 refrigeration tons, total renewable energy HVAC system 7,800 refrigeration tons (25.6% of total load)",
          "Guacheon National Science Museum, Seoul, Korea Closed Loop Ground Source Heat Pump System, Capacity 450 Refrigeration Tons, 130 Vertical Boreholes, HX Depth 660’",
          "Seoul City Hall, Seoul, Korea Closed Loop Ground Source Heat Pump System, Capacity 1,030 Refrigeration Tons, 280 Vertical Boreholes, HX Depth 670’ (boreholes located under building footprint)",
          "Busan University Hospital, Busan, Korea",
          "Phase I – Closed Loop Ground Source Heat Pump System, 880 Refrigeration Tons, 240 Vertical Boreholes, HX Depth 665’",
          "Phase II – Closed Loop Ground Source Heat Pump System, 1260 Refrigeration Tons, 360 Vertical Boreholes, HX Depth 665’",
          "Phase III – Closed Loop Ground Source Heat Pump System, 600 Refrigeration Tons, 172 Vertical Boreholes, HX Depth 650’",
          "Communication Center, Camp Humphreys, Pyeontaek, Korea (Hardened Facility Located Underground N+2 primary/backup/backup)",
          "Primary – Closed Loop Ground Source Heat Pump System, Capacity 3500 Refrigeration Tons, 1188 Vertical boreholes – with four 30’ length ISCO underground valve vaults, HX Depth 750’",
          "Secondary – Open Loop Ground Source Heat Pump System, 2000 Refrigeration Tons, four source wells 1265’ (standing column with 30% bleed rate – backup source using SS Plate Heat Exchangers)",
          "Daegu Bachelor Officers Quarters, Daegu, Korea Closed Loop Ground Source Heat Pump System, Capacity 250 Refrigeration Tons, 80 Vertical Boreholes, HX Depth 672’ (200 RTons heating/cooling – 50 RTons hot water generation)",
          "US Army Airbase K16, Seongnam, Korea (First Phase – Airbase Retrofit to GSHP Systems) Closed Loop Ground Source Heat Pump System, Capacity 580 Refrigeration Tons, 175 Vertical Boreholes, HX Depth 660’"
        ]
      }
    ],
    image: "/images/team/garry-sexton.webp",
    imageAlt: "Garry Sexton Head Shot",
    leadership: true
  },
  {
    slug: "ian-talbot",
    name: "Ian Talbot",
    role: "Engineering and Design",
    credentials: null,
    email: "italbot@greyedgegroup.com",
    phone: "385-348-0281",
    website: null,
    linkedin: null,
    bio: [
      "Ian grew up working on his family’s cherry orchard, where he developed a strong work ethic and a practical, hands-on approach to problem solving that continues to influence his engineering work.",
      "Ian earned his degree in Energy Engineering (BS) from Weber State University and is a certified Engineer in Training (EIT), having passed the Fundamentals of Engineering (FE) exam. As part of his senior project, he developed a solar gain calculator used to estimate solar heat gain on buildings, reflecting his interest in applied energy analysis.",
      "His work emphasizes analytical rigor, technical accuracy, and continuous improvement, with a focus on applying engineering principles to real-world challenges. Outside of work, he enjoys hands-on technical hobbies, including 3D printing, vacuum casting, and microprocessor and microcontroller-based projects.",
      "American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE)"
    ],
    sections: [],
    image: "/images/team/ian-talbot.webp",
    imageAlt: "A Head Shot of Ian Talbot who focuses on the engineering and design of complex thermal energy systems for GreyEdge.",
    leadership: false
  },
  {
    slug: "jaiden-marriott",
    name: "Jaiden Marriott",
    role: "Engineer in Training - EIT",
    credentials: null,
    email: "jmarriott@greyedgegroup.com",
    phone: null,
    website: null,
    linkedin: null,
    bio: [
      "A native of Ogden, Utah, Jaiden Marriott is an Energy Engineering graduate of Weber State University and an Engineer in Training at The GreyEdge Group. He focuses on the engineering and design of complex thermal energy systems, energy modeling, and district energy feasibility studies that support the transition to low-carbon, resilient infrastructure.",
      "Jaiden’s senior research at Weber State analyzed the geothermal bore field at the Engineering Building, where he developed a detailed energy model to estimate ground temperature behavior, evaluated system performance, and implemented optimized control strategies to improve system operation. Those experiences helped shape his systems-focused approach to geothermal and electrified thermal networks.",
      "At The GreyEdge Group, Jaiden contributes to large-scale feasibility studies, energy modeling efforts, and thermal system design projects, helping clients assess and optimize pathways to electrification and decarbonization. His work reflects a dedication to practical, infrastructure-first solutions for district energy retrofit and renewable integration.",
      "Outside of technical work, Jaiden is passionate about sustainability, renewable energy, and building lasting relationships, one of his favorite parts of the industry. He enjoys connecting with others who share an interest in advancing clean energy solutions and sustainable communities."
    ],
    sections: [],
    image: "/images/team/jaiden-marriott.webp",
    imageAlt: "A Head Shot of Jaiden Marriott who is in an Engineering role at GreyEdge",
    leadership: false
  },
  {
    slug: "john-mclennan",
    name: "John McLennan",
    role: "Subsurface and Geoscience Advisor",
    credentials: null,
    email: "jmclennan@greyedgegroup.com",
    phone: "801-634-4412",
    website: "https://faculty.utah.edu/u0607793-JOHN_DAVID_MCLENNAN/teaching/index.hml",
    linkedin: null,
    bio: [
      "Since October 2009, Professor John McLennan has been a faculty member in the Department of Chemical Engineering at the University of Utah. He has been a Senior Research Scientist at the Energy & Geoscience Institute and an Adjunct Professor in the Department of Civil Engineering at the University of Utah since January 2008. He has a Ph.D. in Civil Engineering from the University of Toronto, awarded in 1980. He has more than thirty-five years of experience with petroleum service and technology companies. He worked for Dowell and Dowell Schlumberger in Denver, Tulsa, and Houston, with TerraTek in Salt Lake City, Advantek International in Houston, and ASRC Energy Services in Anchorage. He has worked on projects concerned with subsurface energy recovery and storage (hydrocarbon, geothermal) in a variety of reservoir environments throughout the world. He is a co-principal investigator on the DOE FORGE project (Frontier Observatory for Research in Geothermal Energy) and an American Rock Mechanics Association (ARMA) Fellow."
    ],
    sections: [
      {
        heading: "Areas of Expertise",
        items: [
          "Subsurface formation characterization from hydraulic, mechanical, and thermal perspectives.",
          "Subsurface engineering including hydraulic stimulation, fluid and slurry injection, and wellbore integrity."
        ]
      },
      {
        heading: "Professional Affiliations and Publications",
        items: [
          "Publications: https://scholar.google.com/citations?user=S6xW5H8AAAAJ&hl=en",
          "Member of AIChE, SPE, SPWLA, ARMA, Geothermal Rising",
          "Fellow of American Rock Mechanics Association (ARMA)",
          "Past President of American Rock Mechanics Association (ARMA)"
        ]
      }
    ],
    image: "/images/team/john-mclennan.webp",
    imageAlt: "A Head Shot of John McLennan.",
    leadership: true
  },
  {
    slug: "mark-smith",
    name: "Mark Smith",
    role: "Geoexchange Design and Installation",
    credentials: "CGD, CGI, AI",
    email: null,
    phone: "801-942-6100",
    website: null,
    linkedin: null,
    bio: [
      "Mark grew up in the in the energy industry, first working in oil and gas before spending 2 years with Sound Geothermal as a GSHP design & installation technician as well as a drillers assistant. After serving ~4 years in the US Navy as a Hospital Corpsman Mark returned to Sound Geothermal. For the past 19 years Mark has been in charge of special projects for Sound Geothermal and is currently Vice President. Mark has worked in the GSHP industry since 2000 and has been involved in the design and implementation of over 45,000 tons of installed capacity in North America. Mark has been involved in a range of projects from HUD housing to mega homes, industrial facilities and University campuses to NASCAR facilities. Sound Geothermal is a design engineering firm, manufacturer’s representative, and distributor for ground source heat pump equipment and accessories. The company is active throughout the western United States and has projects in a total of 31 states. Mark has extensive training in system load evaluation, ground loop heat exchanger design, solar thermal systems, system hydraulics, heat pump operations, heat pump equipment selection and system troubleshooting. Mark is an AEE Certified GeoExchange Designer, IGSHPA Certified Geothermal inspector and IGSHPA Accredited Installer. Mark also holds a Utah General Contractor’s License, HVAC License & Boiler License."
    ],
    sections: [
      {
        heading: "Areas of Expertise",
        items: [
          "Applying a “Systems” approach to GHPC design is a key to making systems function economically, correctly and with a minimum carbon footprint. This requires complete integration of the Ground Loop Heat Exchanger(GLHE), mechanical piping, and controls. As an early adopter of this approach, we have been able to integrate systems from several HUD homes to University campuses. Mixed use applications in City‐scape and Campus environments provide ideal opportunity to bring together wasted energy collection and re‐use that energy (Energy HighwayTM); significantly increasing System Coefficient of Performance (SCOP). This approach not only increases efficiency or Least Energy PathTM) but also dramatically reduces greenhouse gas emission and water consumption.",
          "Assessments to determine economic and technical feasibility of GSHP systems for commercial GSHP projects",
          "Design and implementation of ground source heat pump systems and associated ground heat exchangers",
          "Large scale Distributed (District) Energy Systems",
          "Control and Sequence of Control review and optimization",
          "Forensic analysis of failed or poorly operating GSHP systems"
        ]
      },
      {
        heading: "Notable Projects & Achievements",
        items: [
          "Colorado Mesa University, Grand Junction Colorado, Development of campus Ambient Temperature Loop (ATL) designed to serve ~4,700 tons, design of GLHE & distribution system for 18 buildings, ~1.5MM^ft and over 250,000 vertical feet of drilled GLHE.",
          "Uintah Basin Medical Center, Roosevelt Utah, ~250,000^ft six building hospital campus, extended care facility, doctor’s clinics, surgery, emergency – Add ATL design to interconnect existing buildings with main hospital and future buildings.",
          "Cashman Equipment Henderson Facility, Cashman Equipment, Las Vegas Nevada. ~ 500,000 ^ ft. (LEED & Hybrid) 900 tons. Multi Building Community Loop",
          "Weber State University, Ogden Utah, Campus incremental conversion from boiler/chiller plant to ATL utilizing existing CW piping."
        ]
      },
      {
        heading: "Professional Affiliations",
        items: [
          "International Ground Source Heat Pump Association (IGSHPA); Member, Certified Geothermal Inspector, Accredited Installer",
          "Association of Energy Engineers (AEE); Member, Certified GeoExchange Designer",
          "American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE); Member"
        ]
      }
    ],
    image: "/images/team/mark-smith.webp",
    imageAlt: "Mark Smith Head Shot",
    leadership: true
  },
  {
    slug: "megan-lim",
    name: "Megan Lim",
    role: "Marketing and Business Development",
    credentials: null,
    email: "mlim@greyedgegroup.com",
    phone: null,
    website: null,
    linkedin: null,
    bio: [
      "At GreyEdge, Megan is a Marketing and Business Development Consultant. She works on communicating thermal energy networks (how they work, their tradeoffs, case studies, etc.) to various stakeholders. She contributes to business development in the Northeast and youth engagement with the TENs industry.",
      "Megan graduated from MIT in 2024 with a bachelor’s degree from the Sloan School of Management. She is exploring how educational systems, industry, governments, and communities-at-large can work together on community challenges, and engage youth while doing so. She is passionate about workforce development, especially through creating more real-world opportunities for students. Starting her senior year in college, she began contributing to a student-alumni proposal to decarbonize MIT’s campus by 2035 through thermal energy networks (MITTEN). While interviewing the top experts in geothermal, she met GreyEdge members and joined the team in May 2025. Before joining GreyEdge, she worked with MIT Office of Sustainability on student engagement, MIT Environmental Solutions Initiative on climate education (including a K-12 geothermal systems curriculum), and MIT D-Lab on supporting student projects for the first TENs college introductory course modeled after the Certified GeoExchange Designer Course (led by Susan Murcott). Megan currently leads Stakeholder Relations for the Geo@MIT student team, supports TENs and youth engagement resource development for Run on Climate, sits on the Cambridge Climate Committee, and co-leads the MA (Student) Cross Campus Climate Coalition.",
      "She is based in Cambridge MA."
    ],
    sections: [
      {
        heading: "Notable Projects & Achievements",
        items: [
          "Created K-12 Geothermal Systems Curriculum with MIT Environmental Solutions Initiative and HEET through MIT’s Day of Climate",
          "Helped launch International District Energy Association’s first Student Session at Campus Energy Conferences in 2025",
          "2024 Energy Tech University Prize’s National Geothermal Technologies Bonus Prize Winner (with Geo@MIT)",
          "2025 US Delegate for the UNFCCC-YOUNGO endorsed youth climate change conference (Local Conference of Youth)",
          "Appointed to City of Cambridge’s Climate Committee, beginning February 2025",
          "Appointed to MIT’s Presidential Advisory Cabinet 2023-2024",
          "Co-chaired the MIT Undergraduate Association’s Innovation Committee and conducted logistics for MIT’s Banana Lounge between 2021-2024"
        ]
      },
      {
        heading: "Affiliations",
        items: [
          "MIT Alumni for Climate Action and College and University Alumni for a Sustainable Planet",
          "Run on Climate",
          "Co-founder and Stakeholder Relations Lead of Geo@MIT, a student consulting group that equips students with cutting-edge research in thermal energy systems to accelerate the decarbonization of campuses and cities",
          "Cross Campus Climate Coalition, which brings together students of higher education institutions to contribute to campus and city climate goals, mainly based in Massachusetts. We are building a cross-sector, intergenerational community of youth and professionals to tackle the climate crisis",
          "Co-Lead of Assembly for Civic Engagement in MA Higher Education, a state-wide initiative to increase student collaboration with each other and the Commonwealth of Massachusetts"
        ]
      }
    ],
    image: "/images/team/megan-lim.webp",
    imageAlt: "A Head Shot of Megan Lim who is a Marketing and Business Development Consultant and works on communicating thermal energy networks for The Grey Edge Group.",
    leadership: false
  },
  {
    slug: "roshan-revankar",
    name: "Roshan Revankar",
    role: "Geothermal Design and Energy Modeling",
    credentials: "PE, CGD, CGI, BESA",
    email: "rrevankar@greyedgegroup.com",
    phone: "405-564-4991",
    website: null,
    linkedin: null,
    bio: [
      "Roshan Revankar is on a mission to make ground source energy affordable. He has expertise in geothermal design and energy modeling and is also involved in writing standards and codes for various organizations.",
      "Roshan holds a master’s degree in Mechanical Engineering from Oklahoma State University and is a certified building simulation analyst by Association of Energy Engineers and certified geothermal designer and inspector by IGSHPA. He is the current Vice Chair of ASHRAE’s technical committee for geothermal and he serves on various technical committees at IAPMO to develop standards and codes for ground source technology.",
      "Roshan is a Professional Engineer, licensed in California. He is based in the Bay area where he enjoys spending his spare time with family, watching and playing cricket and selling some real estate."
    ],
    sections: [
      {
        heading: "Areas of Expertise",
        items: [
          "Roshan enjoys the design process for ground source and has worked with several facets in this industry including heat pump manufacturers, drillers and installers. He has trained over 300 professionals in the last 12 years.",
          "Roshan is a co-founder and partner at Genesys NZE working to develop low cost ground heat exchangers. He is also a partner at Melink Zero where the team has advanced thermal energy storage products using phase change materials. Roshan has previously served as the Executive Director at IGSHPA where he developed training and membership programs and also established the organization internationally. He has served the role of an industry advocate and has been invited as a speaker nationally and internationally."
        ]
      },
      {
        heading: "Professional Affiliations and Publications",
        items: [
          "Member – International Ground Source Heat Pump Association (IGSHPA",
          "Member – American Society of Heating, Refrigeration and Air-conditioning Engineers (ASHRAE)",
          "Member and Contributor – International Association of Plumbing & Mechanical Officials (IAPMO)",
          "Publications",
          "Component modeling of Air-to-Refrigerant Heat Transfer",
          "An experimental study on using a mass radiant floor with geothermal system as thermal battery of the building",
          "Patents",
          "Super Hybrid heat pump system and method"
        ]
      }
    ],
    image: "/images/team/roshan-revankar.webp",
    imageAlt: "Roshan Revankar Head Shot",
    leadership: true
  }
]

const orderIndex = (slug: string) => {
  const i = (teamOrder as readonly string[]).indexOf(slug)
  return i === -1 ? Number.MAX_SAFE_INTEGER : i
}
team.sort((a, b) => orderIndex(a.slug) - orderIndex(b.slug))

export const leadership = team.filter((m) => m.leadership)

export const getMember = (slug: string) => team.find((m) => m.slug === slug)
